# Programação e Análise de Dados com Python
##### Programa de Pós-Graduação em Economia - PPGE

## Python - Vetores e Matrizes

###### Prof. Hilton Ramalho
###### Prof. Aléssio Almeida

## Objetivo
Desenvolver operações básicas de vetores e matriz no `Python`.


## Conteúdo
1. [Definição](#intro)
2. [Entrada de Matrizes](#matrix)
3. [Operações básicas em matrizes](#operacoes)
4. [Estatísticas básicas](#stats)
5. [Reshape](#reshape)
6. [Operações de álgebra linear](#linalg)
7. [Gerador de Valores Aleatórios](#random)
8. [Exercícios](#exerc)



<a name='intro'></a>
# Vetores e Matrizes

- Um vetor pode ser definido como uma coleção de números com comprimento, sentido e direção.
- Matrizes são **arranjos vetores** em dois espaços (linha/coluna) com diversas aplicações em matemática, estatística, econometria...
- Arrays são **arranjos matrizes**.
- A biblioteca `numpy` possui uma série de funcões específicas para vetores e matrizes.

## Vetor

- Vamos escrever o seguinte vetor linha:
\begin{equation}
A=
\begin{bmatrix}
    1 & 2 & 3\\
\end{bmatrix}
\end{equation}

- Vamos escrever o seguinte vetor coluna:
\begin{equation}
A=
\begin{bmatrix}
    1 \\ 2 \\ 3 \\
\end{bmatrix}
\end{equation}

- Normalmente, usamos o termo **matriz** quando há mais de uma dimensão: espaço-linha e o espaço-coluna.

\begin{equation}
A=
\begin{bmatrix}
    x_{11}       & x_{12} & x_{13} & \dots & x_{1m} \\
    x_{21}       & x_{22} & x_{23} & \dots & x_{2m} \\
    \vdots & \vdots & \vdots & \ddots & \vdots\\
    x_{n1}       & x_{n2} & x_{n3} & \dots & x_{nm}\\
\end{bmatrix}
\end{equation}

## Especificações `numpy` de vetores e matrizes

- Toda matriz deve estar contida entre `[]` e depois entre `()`, i.e., `matrix([...])`
- Cada linha é formada por uma lista
- Todo vetor linha ou coluna pode ser escrito usando **o método** `array(...)`. Caso queiramos gerar uma matriz usamos e mesmo método: `array([...])`
- Todo array é da classe `ndarray`.


## Documentação do pacote `numpy`

- [https://numpy.org/doc/](https://numpy.org/doc/)

## Instalação do pacote `numpy`

```
 pip install numpy
```

## Importação da biblioteca ou pacote `numpy`

- Importação é feita com um apelido no intuito de simplicar as chamadas dos
  métodos.

```
import numpy as np
```

## Ajuda

Verificar todos os detalhes do pacote:

```
import numpy
help(numpy)
```

In [1]:
# Instalação do pacote numpy no NoteBook Colab
!pip install numpy

#### Carregando o pacote `numpy` e ajuda

In [ ]:
# Carregando a biblioteca atribuindo um apelido
import numpy as np
# Ajuda
help(np)

#### Arrays como uma generalização de vetores e matrizes

- Uma array é uma coleção de matrizes. Por sua vez, uma matriz é uma coleção de vetores. Um vetor é um coleção de números.
- Portanto, em última análise, usamos o conceito de `array` no `numpy` para representar vetores e matrizes.

**Exemplo** - Carregando o pacote `numpy` e criando um vetor-linha. 
- No `numpy`, por padrão, um vetor será armazendo na forma de matriz-linha.
- Usaremos o método `array`. Ele espera listas como argumento.

In [5]:
# Carregando a biblioteca
import numpy as np

# Criando um vetor-linha
# Usamos o método array - espera listas como argumento.
# Esse vetor equivale a uma matriz de ordem (1 x 3)
v = np.array([1,2,3])
print(v)

[1 2 3]


In [6]:
# Tipo do objeto
type(v)

numpy.ndarray

- Por padrão, os vetores criados pelo `numpy` ficam na forma de matriz linha.
- No entanto, podemos escrever o seguinte vetor na forma de matriz coluna:
- Para numpy você deve escrever uma matriz 3 x 1 (três linhas/ 1 coluna)
\begin{equation}
B=
\begin{bmatrix}
    1\\
    2\\
    3\\
\end{bmatrix}
\end{equation}

In [8]:
# Criar um vetor na forma matrix-coluna
# Vetor (1,2,3) - forma tupla
# Passar para forma matriz - coluna
u = np.array( [ [1], [2], [3]   ]  )
print(u, type(u))

[[1]
 [2]
 [3]] <class 'numpy.ndarray'>


#### Usando o método reshape para transpor um vetor-linha

In [10]:
# Passar um vetor-linha e tem seguida transpor para a forma vetor-coluna

v = np.array( [1, 2, 3]  ).reshape(3,1)
v

array([[1],
       [2],
       [3]])

#### Propriedades de uma Array

In [13]:
# Vamos criar o vetor-linha (array)
v = np.array( [4,-2,0,1,6] )
print(v, type(v))

[ 4 -2  0  1  6] <class 'numpy.ndarray'>


In [16]:
# Checando algumas propriedades de uma array

# Formato
v.shape

(5,)

In [17]:
# Dimensão da array (total de objetos)
v.ndim

1

In [18]:
# Total de elementos dos objetos
v.size

5

In [19]:
# Tipagem dos elementos
v.dtype

dtype('int64')

In [20]:
u = np.array( [0.5, -2.3, 2.3, 5.6])
u

array([ 0.5, -2.3,  2.3,  5.6])

In [21]:
u.dtype

dtype('float64')

#### Ajuda - visão geral dos métodos para arrays

In [ ]:
help(np.array)

## Consulta e Fatiamento de vetores

- Podemos acessar os elementos de um vetor de forma similar ao que fizemos
  para acessar elementos de um objeto lista no Python, ou seja, usando 
  a indexação para frente e para trás.

In [22]:
# Criando um vetor-linha - usando a função range
x = np.array( range(7,0,-1) )
x

array([7, 6, 5, 4, 3, 2, 1])

In [23]:
x[0] # primeiro elemento do vetor

7

In [24]:
x[-1] # última elemento do vetor

1

In [26]:
# Selecionando todos os valores antes do 3º elemento
x[:3]

array([7, 6, 5])

In [27]:
# Selecionando todos os valores a partir do 3º elemento
x[3:]

array([4, 3, 2, 1])

In [ ]:
# Selecionando o último elemento
x[-1]

1

## Operações básicas com vetores

- Adição
- Subtração
- Multiplicação

**Exemplo** - Criando vetores com mesma dimensão.

In [28]:
# Vetor-linha a
a = np.array([1, 2, 3])
# Vetor-linha b
b = np.array([0, 1, 1])
print(f' a = {a}\n b = {b}')

 a = [1 2 3]
 b = [0 1 1]


In [29]:
# Vetores com a mesma dimensão
print(a.size)
print(b.size)

3
3


**Adição** - **Somar dois vetores** - Somamos elemento por elemento e o resultado será um novo vetor. Usamos o operador `+`

In [31]:
# Adição de elemento por elemento
c = a + b
c

array([1, 3, 4])

**Subtração de vetores** - subtraimos elemento por elemento e o resultado será um novo vetor. Usamos o operador `-`.

In [34]:
# Subtração de elemento por elemento
c = a - b
print(c)

[1 1 2]


**Multiplicação de elementos** - multiplicamos elemento por elemento e o resultado será **um novo vetor**. Usamos o operador `*`.

**Observação** - Não se trata da operação de multiplicação de vetores da álgebra linear e sim uma multiplicação interativa de elemento por elemento.

In [36]:
# Multiplicação elemento por elemento - resulta será um novo vetor
c = a * b
c

array([0, 2, 3])

#### Produto escalar de vetores

- Multiplicar vetores de mesma dimensão para produzir um número. 
- vetor-linha x vetor-coluna
- Usamos o operador `@` para fazer a multiplicação de vetores - produto escalar.

In [37]:
# Criar os dois vetores-linha
a = np.array( [ 0, -2, 4 ] )
b = np.array( [ 3, 2, 2 ] )
print(a, b)

[ 0 -2  4] [3 2 2]


In [38]:
# Produto interno (escalar)
a @ b

4

In [42]:
# Produto interno (escalar)
b @ a

4

<a name='matrix'></a>
# Entrada de Matrizes


- Vamos escrever a seguinte matriz:
\begin{equation}
A=
\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9\\
\end{bmatrix}
\end{equation}

## Sintaxe dos métodos 

- Podemos criar matrizes no `numpy` a partir de dois métodos: 
- O método `.array` e o método `.matrix`.
- Observe a sintaxe de construção do objeto onde passamos uma lista
  aninhada, onde cada lista filha é um vetor linha da matriz.
```
np.array( [ [ vetor linha 1 ], [ vetor linha 2], ..., [vetor linha n] ] )
np.matrix( [ [ vetor linha 1 ], [ vetor linha 2], ..., [vetor linha n]] )
```

## Ajuda

```
import numpy as np
help(np.array)
help(np.matrix)
```

**Exemplo** - Criando uma matriz com o método `.matrix`.

In [43]:
# Empilhando vetores no espaço-linha - usando o método matrix
# Vamos criar três listas
v1 = [1,2,3]
v2 = [4,5,6]
v3 = [7,8,9]

# Criando uma matriz de ordem 3 x 3
np.matrix([ v1,v2,v3 ])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**Exemplo** - Criando uma matriz com o método `.array`.

In [44]:
# Criando matriz usando o método array - matrix 3 x 3
a = np.array([ [1,2,3], [4,5,6], [7,8,9]  ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
# Criando matriz usando o método array - matrix 3 x 2
a = np.array([ [3,4], [-2,-1], [0,1]  ])
a

array([[ 3,  4],
       [-2, -1],
       [ 0,  1]])

In [46]:
# Total de elementos da matriz
a.size

6

In [47]:
# Dimensão da matriz
a.shape

(3, 2)

In [48]:
# Criando matriz usando o método array - matrix 2 x 3
a = np.array([ [-1,0,0], [5,7,10] ])
a

array([[-1,  0,  0],
       [ 5,  7, 10]])

In [49]:
a.shape

(2, 3)

In [50]:
# Criando matriz usando o método array - matrix 2 x 2
a = np.array([ [3,4], [0,1] ])
a

array([[3, 4],
       [0, 1]])

In [51]:
a.shape

(2, 2)

**Exemplo** - **Transformando listas em Array** - Criando uma matriz a partir do empilhamento de listas de mesma dimensão nas linhas da matriz. Usamos o método `.asarray`. Veja a ajuda:
```
import numpy as np
help(no.asarray)
```

In [25]:
# Imagine o caso em que temos vetores - .asarray - empilhar lista para uma array (matriz)
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
# Empilhando
mat_a = np.asarray([a,b,c])
mat_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Consulta e Fatiamento de matrizes

- Lógica de indexação de arrays/matrizes segue a mesma indexação de lista aninhadas (agrupadas)

```
[  [ vetor-linha1  ], [ vetor linha2]      ]
```
- vetor-linha1 - ocupa a posição 0 na lista principal
- vetor linha2 - ocupa a posição 1 na lista principal

- Se vetor-linha1 = [2,3,4], o elemento 3 ocupa a posição 1 nesta lista
- Se vetor-linha2 = [0,5,1], o elemento 1 ocupa a posição 2 nesta lista

```
[  [2,3,4], [0,5,1]  ]
```

Então, se a matriz (2 x 3) é dada por:
```
A = np.array( [ [2,3,4], [0,5,1] ] )
```

Na matemática queremos acessar, por exemplo, o elemento de A da linha 1 e coluna 2, ou seja, 3.
No `numpy` ele está indexado por:

A linha 1 - ela ocupa a posição 0 na lista principal que forma a array/matriz:
```
A[0,...]
```
Por outro lado, o elemento 3 da lista [2,3,4] ocupa a posição 1 nesta lista. Portanto:
```
A[0,1]
```
Equivale a acessar o elemento da matriz A da linha 1/coluna 2, que no `numpy`
equivale ao elemento indexado por [0,1]




**Exemplo** - Acessando o elemento A[1,1] da matriz A. Na indexão do Python equivale a acessar a linha de posição 0 e o elemento desta linha que ocupa a posição 0:

In [52]:
# Criamos a array (matrix 2 x 3)
a = np.array( [ [2,3,4], [0,5,1] ] )
a


array([[2, 3, 4],
       [0, 5, 1]])

In [53]:
# Acessar o elemento a11 - elemento na primeira linha e na primeira coluna
a[0,0]

2

In [54]:
# Selecionar a última linha
a[-1]

array([0, 5, 1])

In [55]:
# Selecionar a primeira linha
a[0]

array([2, 3, 4])

In [62]:
# Todas as linhas anteriores a linha de posição 1
# No caso será a primeira linha - em seguida acessamos
# os elementos dessa linha - começam na posição 0 e antes da posição 2
a[:1,0:2]

array([[2, 3]])

In [28]:
# Duas primeiras linhas e todas as colunas da matriz
# :2 - Todos os elementos-linha antes da linha de posição 2
# : - Todas as colunas
a[:2,:]

array([[2, 3, 4],
       [0, 5, 1]])

In [29]:
# Todas as linhas e a segunda coluna
a[:,1]

array([3, 5])

## Descrevendo uma matriz

- Podemos descrever propriedades de uma matriz/vetor:
- Formato da matriz/vetor com o método `.shape`
- Total de elementos da matriz/vetor com método `.size`
- Dimensão da matriz/vetor com o método `.dim`

- Todos eles são submétodos de um objeto `numpy array`.

**Exemplo** - Criando uma matriz com o método `.array`.

In [63]:
# Vamos criar a matriz A (3 x 3)
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

**Exemplo** - Verificando o formato da matriz.

In [64]:
a.shape

(3, 3)

**Exemplo** - Verificando o total de elementos da matriz.

In [65]:
# Número de elementos = número linhas * número de colunas
a.size

9

**Exemplo** - Verificando a dimensão da matriz (espaço-linha e espaço-coluna)

In [66]:
# Número de dimensões - espaço linha e o espaço coluna
a.ndim

2

### Matrizes especiais

Na família de matrizes temos um conjunto de matrizes especiais que podem ser usadas para facilitar várias tarefas de programação envolvendo àlgebra linear.

- Matriz nula - todos os elementos iguais a zero.
- Matriz identidade (quadrada) - matriz quadrada (diagonal) com todos os elementos da diagonal principal iguais a 1 e os demais iguais a zero.
- Matriz com elementos repetidos - matriz cujos elementos são todos iguais

**Exemplo** - criando matrizes nulas - método `.zeros`.

```
import numpy as np
help(np.zeros)
```


In [ ]:
# Vetor nulo
v = np.zeros(6)
print(v)

[0. 0. 0. 0. 0. 0.]


In [ ]:
# Vetor nulo
v = np.zeros(2)
print(v)

[0. 0.]


In [ ]:
# Vetor nulo com elementos inteiros
v = np.zeros(6, dtype='int')
print(v)

[0 0 0 0 0 0]


In [ ]:
# Vetor nulo
v = np.zeros(2, 'int')
print(v)

[0 0]


In [ ]:
# Matriz com valores zerados - método zeros
# passamos o shape como uma tupla (total de linhas, total de colunas)
v = np.zeros((4,3), 'int')
v

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Matriz com valores zerados - método zeros
# passamos o shape como uma tupla (total de linhas, total de colunas)
v = np.zeros((2,5), 'int')
v

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Matriz com valores zerados - método zeros
# passamos o shape como uma tupla (total de linhas, total de colunas)
v = np.zeros((4,4), 'int')
v

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Exemplo** - Criando uma matriz com elementos repetidos e iguais a 1. Usamos o método `.ones`. 

```
import numpy as np
help(np.ones)

```

In [ ]:
# Matriz com valores 1 - método ones
v = np.ones((4,3), 'float')
v

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# Matriz quadrada
np.ones((2,2), 'int')

array([[1, 1],
       [1, 1]])

In [ ]:
# Vetor
np.ones(10, 'int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Exemplo** - Criando uma matriz com elementos repetidos e iguais. Usamos o método `ones` seguido por multiplação da matriz por um escalar.

In [ ]:
# Matriz com valores repetidos - criarmos a matriz com elementos = 1 e 
# Multiplicamos essa matriz por um escalar
np.ones((4,3), 'int')*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# Matriz com valores repetidos - criarmos a matriz com elementos = 1 e 
# Multiplicamos essa matriz por um escalar
np.ones((3,3), 'int')*-2

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

## Matriz identidade

- Para a criação de uma matriz identidade usamos o método `.identity`.

## Ajuda

```
import numpy as np
help(np.identity)
```

**Exemplo** - Criando uma matriz identidade 2 x 2

In [ ]:
# Criar uma matriz identidade 2 x 2
A = np.identity(2)
print(A)

[[1. 0.]
 [0. 1.]]


**Exemplo** - Criando uma matriz identidade com elementos números inteiros.

In [ ]:
# Criar uma matriz identidade 2 x 2 - elementos inteiros
A = np.identity(2, 'int')
print(A)

[[1 0]
 [0 1]]


In [ ]:
# Matriz identidade - método identity
I = np.identity(10, 'int')
I

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

**Exemplo** - Criando uma matriz diagonal a partir de uma matriz identidade multiplicada por um escalar.

In [ ]:
# Matriz diagonal - matriz identidade vezes um escalar
D = np.identity(5, 'int')*5
print(D)

[[5 0 0 0 0]
 [0 5 0 0 0]
 [0 0 5 0 0]
 [0 0 0 5 0]
 [0 0 0 0 5]]


<a name='operacoes'></a>
# Operações com os elementos de matrizes



**Exemplo** - Criando uma matriz.

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

**Exemplo** - Soma de cada elemento com um escalar.

In [ ]:
# Somar 100 a todos os elementos da matriz
A + 100

**Exemplo** - Subtração de cada elemento com um escalar.

In [ ]:
# Subtrair 100 a todos os elementos da matriz
A - 10

**Exemplo** - multiplicação de cada elemento com um escalar.

In [ ]:
# Multiplicar por 10 todos os elementos da matriz
A * 10

**Exemplo** - Divisão de cada elemento com um escalar.

In [ ]:
# Dividir por 10 todos os elementos da matriz
A / 10

**Exemplo** - Potência de cada elemento com um escalar.

In [ ]:
# Potencializar por 2 todos os elementos da matriz
A ** 2

## Operações com matrizes

- Soma
- Multiplicação

**Exemplo** - Criamos duas matrizes.

In [ ]:
# Soma de matrizes
A = np.array([ [1,2], [0,1] ])
B = np.array([ [9,2], [0,-1] ])   

print(A, B)

[[1 2]
 [0 1]] [[ 9  2]
 [ 0 -1]]


**Exemplo** - Soma de duas matrizes de mesma dimensão.

In [ ]:
# Adição
A + B

array([[10,  4],
       [ 0,  0]])

**Exemplo** - Subtração de duas matrizes de mesma dimensão.

In [ ]:
# Subtração
A - B

array([[-8,  0],
       [ 0,  2]])

**Exemplo** - Multiplicação elemento por elemento de matrizes mesma dimensão.

In [ ]:
# Multiplicação elemento por elemento
A * B

array([[ 9,  4],
       [ 0, -1]])

## Multiplicação de matrizes 

- Para a multiplicação de objetos que são matrizes usamos  o método `.matmul`.

## Ajuda

```
import numpy as np
help(np.matmul)
```

**Exemplo** - multiplicação de duas matrizes - espaço-linha de A deve ter a mesma dimensão do espaço-coluna de B para as operações de produto interno de vetores.

In [ ]:
# Multiplicação de matrizes
np.matmul(A, B)

array([[ 9,  0],
       [ 0, -1]])

In [ ]:
# Vetores - produto interno ou produto escalar 
a = np.array([1,2])
b = np.array([0,1])
np.matmul(a,b)

2

## Ordenar valores de uma matriz

- Em algumas situações particulares podemos ordenar os elementos de uma matriz 
conforme uma linha ou coluna.

- Para tanto, usamos o método `.argsort`.

## Ajuda

```
import numpy as np
help(np.argsort)
```

In [ ]:
A = np.array([[4, 5, 6],
              [2, 3, 1],
              [7, 8, 9]])

#Ordenada pelos valores da primeira coluna
indice = A[:,0].argsort(axis=0)
print(indice)

[1 0 2]


In [ ]:
A_ordenada = A[indice, :]
A_ordenada

array([[2, 3, 1],
       [4, 5, 6],
       [7, 8, 9]])

<a name='stats'></a>
# Estatísticas básicas

Podemos calcular estatísticas básicas a partir dos elementos de uma matriz, seja filtrando por linha ou coluna. Para tanto, podemos usar alguns métodos:

- Valor máximo - método `.max`.
- Valor mínimo - método `.mix`.
- Média - método `.mean`.
- Média excluíndo dados faltantes - método `.nanmean`.
- Variância - método `.var`.
- Desvio padrão `.std`.
- Soma `.sum`.

- Observe os exemplos abaixo:



In [ ]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Máximo valor da matriz
np.max(A)

9

In [ ]:
# modo alternativo
A.max()

9

In [ ]:
print(A)
# Máximo valor de cada coluna da matriz
np.max(A, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [ ]:
# Máximo valor de cada linha da matriz
np.max(A, axis=1)

array([3, 6, 9])

In [ ]:
print(A)
# Valor Mínimo
np.min(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

In [ ]:
# Valor Mínimo por coluna
np.min(A, axis=0)

array([1, 2, 3])

In [ ]:
# Valor Mínimo por linha
np.min(A, axis=1)

array([1, 4, 7])

In [ ]:
# Somatório
print(A)
np.sum(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [ ]:
# Soma por coluna
print(A)
np.sum(A, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [ ]:
# Soma por linha
print(A)
np.sum(A, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [ ]:
print(A)
# Média
np.mean(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0

In [ ]:
# Média por coluna
print(A)
np.mean(A, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [ ]:
# Média por linha
print(A)
np.mean(A, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [ ]:
# Variância
print(A)
np.var(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6.666666666666667

In [ ]:
# Variância por coluna
print(A)
np.var(A, axis = 0).round(2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([6., 6., 6.])

In [ ]:
# Variância por linha
print(A)
np.var(A, axis = 1).round(2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([0.67, 0.67, 0.67])

In [ ]:
# Desvio-padrão
print(A)
np.std(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.581988897471611

In [ ]:
# Retorna DP por coluna
np.std(A, axis = 0).round(1)

array([2.4, 2.4, 2.4])

In [ ]:
# Retorna DP por linha
np.std(A, axis = 1).round(1)

array([0.8, 0.8, 0.8])

## Exercício

- Suponha que uma turma possui as seguintes notas:

|Aluno | AV1 | AV2 | AV3|
|---|---|---|---|
|A| 10 | 8 | 7 |
|B| 2 | 9 | 10 |
|C| 4 | 6 | 4 |


- Represente as notas acima em uma matriz `A`, calculando a média e desvio-padrão por aluno e por avaliação. Escreva o resultado em um dicionário.


In [ ]:
# Criamos a matriz de notas
A = np.array([ [10,8,7], [2,9,10], [4,6,4] ])
A

array([[10,  8,  7],
       [ 2,  9, 10],
       [ 4,  6,  4]])

 - Criar um dicionário para guardar os resultados

```
  { "aluno": { "media": <valor>, "dp": <valor> }, 
  "prova": { "media": <valor>, "dp": <valor> } }
```

In [ ]:

resultado = {
    'aluno':{
        'media': np.mean(A, axis=1).round(1), 
        'dp': np.std(A, axis=1).round(1)
    },
    'prova': {
        'media': np.mean(A, axis=0).round(1), 
        'dp': np.std(A, axis=0).round(1)
    }
}
resultado

{'aluno': {'dp': array([1.2, 3.6, 0.9]), 'media': array([8.3, 7. , 4.7])},
 'prova': {'dp': array([3.4, 1.2, 2.4]), 'media': array([5.3, 7.7, 7. ])}}

## Exercício

- Suponha que uma turma possui as seguintes notas:

|Aluno | AV1 | AV2 | AV3|
|---|---|---|---|
|A| 10 | 8 | 7 |
|B| 2 | 9 | 10 |
|C| 4 | 6 | 4 |
|D|0|5|F|


- Represente as notas acima em uma matriz `A`, calculando a média e desvio-padrão por aluno e por avaliação. Trate a falta do aluno D como uma informação faltante.


## Representar um elemento faltante

-  Método `np.nan`.


In [ ]:
A = np.array([[10,8,7], [2,9,10], [4,6,4], [0,5, np.nan]])
A



array([[10.,  8.,  7.],
       [ 2.,  9., 10.],
       [ 4.,  6.,  4.],
       [ 0.,  5., nan]])

In [ ]:
resultado = {'aluno':{'media': np.nanmean(A, axis=1).round(1), 'dp': np.nanstd(A, axis=1).round(1)},
             'prova': {'media': np.nanmean(A, axis=0).round(1), 'dp': np.nanstd(A, axis=0).round(1)}}
resultado

{'aluno': {'dp': array([1.2, 3.6, 0.9, 2.5]),
  'media': array([8.3, 7. , 4.7, 2.5])},
 'prova': {'dp': array([3.7, 1.6, 2.4]), 'media': array([4., 7., 7.])}}

In [ ]:
av1=resultado['prova']['media'][0]
av2=resultado['prova']['media'][1]
av3=resultado['prova']['media'][2]
print(f'''
Médias da Turma
-------------------
1ª Avaliação: {av1}
2ª Avaliação: {av2}
3ª Avaliação: {av3}
''')


Médias da Turma
-------------------
1ª Avaliação: 4.0
2ª Avaliação: 7.0
3ª Avaliação: 7.0



<a name='reshape'></a>
# Reshape Vetores e Matrizes

- O `reshape` permite reestruturar uma matriz para mantermos os mesmos dados, mas com uma nova organização de linhas e colunas.

- O único requisito é que o formato da matriz original e da nova contenha o mesmo número de elementos.


In [ ]:
# Criando um vetor
import numpy as np
A = np.array([range(0,12)])
print(A)
A.shape

[[ 0  1  2  3  4  5  6  7  8  9 10 11]]


(1, 12)

**Exemplo** - usamos o método `.reshape` para transformar um vetor em uma matriz distribuindo os elementos sequenciamente por linhas.

In [ ]:
# Reshape 2x6
A.reshape(2, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

**Exemplo** - usamos o método `.reshape` para transformar uma matriz outra matriz distribuindo os elementos sequenciamente por linhas conforme o formato desejado.

In [ ]:
B = A.reshape(3,4)
B

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

**Exemplo** - usamos o método `.reshape` para transformar uma matriz em vetor distribuindo os elementos sequenciamente.

In [ ]:
# Transformar uma matriz em uma unica dimensao
# o valor -1 garante a mundança de todos os elemenos
B.reshape(1, -1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [ ]:
B.reshape(-1, 1)
print(B)

Exemplo - usamos o método `.flatten` para transformar um vetor em uma matriz distribuindo os elementos sequenciamento por linhas.

In [ ]:
# Outra forma de tornar a matriz em 1-D
B.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

## Matriz Transposta

- A transposição é uma operação comum em álgebra linear na qual os índices de coluna e linha de cada elemento são trocados. Ou seja, alteramos as dimensões dos espaços linha e coluna.

- No Python usamos o método `.T` para efetuar essa operação.



In [ ]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11,12]])
A

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
A.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
print(f'Matriz original\n {A}\n\n Matriz transposta\n{A.T}')

Matriz original
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

 Matriz transposta
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
print(A.shape, A.T.shape)

(3, 4) (4, 3)



- OBS: tecnicamente, um vetor não pode ser transposto porque é apenas uma coleção de valores.


In [ ]:
# Vetor transposto!
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Um vetor declarado como matriz, porém pode ser transposto
np.matrix([[1, 2, 3, 4, 5, 6]]).T

matrix([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

<a name='linalg'></a>
# Operações de álgebra linear

## Posto matricial

- O posto (rank) de uma matriz é o **número de linhas não-nulas da matriz** quando transformada na forma escalonada por linhas.

- Equivalentemente, corresponde ao número de linhas ou colunas linearmente independentes da matriz.

- O posto tem implicações em relação à independência linear e a dimensão de um espaço vetorial.

- NumPy possui uma função *linear algebra*: `np.linalg.matrix_rank( )`

$$rank(A_{n,m})\leq \min(n,m)$$

## Ajuda

```
import numpy as np
help(np.linalg)
```



**Exemplo** - calculando o posto da matriz A

In [ ]:
# Criamos a matriz A
A = np.array([[1, 2], [2, 4]])
A

array([[1, 2],
       [2, 4]])

In [ ]:
# Calcular o posto da matriz escalonada
np.linalg.matrix_rank(A)

1

## Eliminação Gaussiana
- Por que A tem duas linhas não nulas e o posto é 1 ?
- O posto é o total de linhas não nulas da matriz escalonada


**Exemplo** 

- Criamos uma **matriz elementar** que opera a troca: L2 <-> L2 - 2L1 seguindo as propriedades teóricas da eliminação Gaussiana. 

- Multiplicamos a matriz A por essa matriz elementar para efetuar uma rodade de escalonado. Só uma rodada será suficiente para nosso exemplo.


Vide (https://en.wikipedia.org/wiki/Gaussian_elimination)[https://en.wikipedia.org/wiki/Gaussian_elimination]


In [ ]:
# Matriz elementar de operação gaussiana
E1 = np.array([[1,0],[-2,1]])
E1

array([[ 1,  0],
       [-2,  1]])

In [ ]:
# Reduzir A para a forma escalonada - observe o número de linhas não nulas
A_gauss = np.matmul(E1, A)
A_gauss

array([[1, 2],
       [0, 0]])

**Exemplos** - Outros casos

In [ ]:
A = np.array([[1, 1, 1], [0, 0, 0]])
print(A)

[[1 1 1]
 [0 0 0]]


In [ ]:
np.linalg.matrix_rank(A)

1

In [ ]:
A = np.array([[1, 1, 1],
              [1, 1, 10],
              [1, 1, 15],
              [1, 2,  2]])
A

array([[ 1,  1,  1],
       [ 1,  1, 10],
       [ 1,  1, 15],
       [ 1,  2,  2]])

In [ ]:
np.linalg.matrix_rank(A)

3

In [ ]:
np.linalg.matrix_rank(A.reshape(2,6))

2

## Diagonal de uma matriz quadrada

- Podemos acessar a diagonal principal de uma matriz quadrada e transformá-la em um vetor usando o método `.diagonal`.

## Ajuda

```
import numpy as np
help(np.diagonal)
```

**Exemplos** - Observe abaixo

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

## Diagonal principal
A.diagonal()

array([1, 5, 9])

In [ ]:
print(A)
# A diagonal logo acima da diagonal principal
A.diagonal(offset=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2, 6])

In [ ]:
# A Diagonal logo abaixo da diagonal principal
print(A)
A.diagonal(offset=-1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 8])

In [ ]:
# A Diagonal mais distante abaixo da diagonal principal
A.diagonal(offset=-2)

array([7])

# Traço de uma matriz

- O traço de uma matriz quadrada é a soma dos valores dos elementos da diagonal principal.

- Podemos usar o método `.trace` para calcular esse número.

## Ajuda

```
import numpy as np
help(np.trace)
```


In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
sum(A.diagonal())
#A.diagonal().sum()

15

In [ ]:
# Usando o método trace
A.trace()

15

# Determinante de uma matriz

- O determinante é um número associado a uma matriz quadrada: $A_{nn}$. Ele tem relação com condição de independência linear dos vetores linha e coluna.
- Por exemplo, o determinante de uma matriz $2 \times 2$ é:
\begin{equation}
    \begin{vmatrix}
        a & b\\
        c & d\\
    \end{vmatrix} = ad - bc
\end{equation}

- Uma expressão geral, para quaisquer $n$ é dada pelo Método do LaPlace:

$$|A|=\sum_{i=1}^k a_{ij} C_{ij},$$
onde $C_{ij}=(-1)^{i+j}M_{ij}$ é o cofator de $A_{ij}$ e $M_{ij}$ é uma matrix formada pela exclusão da linha $i$ e coluna $j$ de $A$.

No `numpy` usamos o método `numpy.linalg.det`.

## Ajuda

```
import numpy as np
help(np.linalg.det)
```


## Exercício

Dada a matriz

\begin{equation}
    A =
    \begin{bmatrix}
        1 & 2\\
        1 & 4\\
    \end{bmatrix},
\end{equation}

calcule o determinante.

In [ ]:
# Modo 1: usando o traço

A = np.array([[1, 2],
              [1, 4]])

#Soma da diagonal principal
a = A.trace() 
#Soma da anti-diagonal
b = np.fliplr(A).trace() 
a - b

2

In [ ]:
# Modo 2: usando o método numpy.linalg.det
A = np.array([[1, 2],
              [1, 4]])

# Determinante
np.linalg.det(A)

2.0

In [ ]:
# Uma nova matriz
B = np.array([[1, 2, 3, 4],
              [2, 4, 6, 0],
              [3, 8, 9, 2],
              [1, 1, 2, 1]])
print(B)
# Determinante
np.linalg.det(B).round(1)

[[1 2 3 4]
 [2 4 6 0]
 [3 8 9 2]
 [1 1 2 1]]


16.0

# Revisitando operações matemáticas diversas com matrizes

## Adição e subtração

In [ ]:
A = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 2]])

B = np.array([[1, 3, 1],
              [1, 3, 1],
              [1, 3, 8]])

In [ ]:
np.add(A, B) # Adição

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
A + B

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
np.subtract(A, B)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
A - B

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

## Multiplicação matricial

$$C(i,j)=\sum_{k=1}^K A(i,k)B(k,j)$$

- Podemos usar o método `.dot` ou o operador `@`


In [ ]:
A = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 2]])

B = np.array([[1, 3, 1],
              [1, 3, 1],
              [1, 3, 8]])

In [ ]:
print(f'A =\n {A} \n\n B = \n {B}')

A =
 [[1 1 1]
 [1 1 1]
 [1 1 2]] 

 B = 
 [[1 3 1]
 [1 3 1]
 [1 3 8]]


In [ ]:
np.dot(A, B)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [ ]:
A @ B

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

- Note a diferença da multiplicação de elemento por elemento

In [ ]:
print(f'A =\n {A} \n\n B = \n {B}')

# E se ao invés de @ usássemos *:
A * B

A =
 [[1 1 1]
 [1 1 1]
 [1 1 2]] 

 B = 
 [[1 3 1]
 [1 3 1]
 [1 3 8]]


array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

# Inversão matricial

- A matriz inversa de uma matriz quadrada $A_{n,n}$ é uma segunda matriz denotada de $A^{-1}$, tal que a equação abaixo sempre será válida:

$$A A^{-1} = A^{-1} A = I$$

- No entanto, uma matriz quadrada pode não possuir uma inversa caso seu determinante seja nulo, dado o teorema abaixo:

$$ A^{-1} = \frac{1}{|A|} \hat{A}  $$

Onde $|A|$ é o determinante de $A$ e $\hat{A}$ é a matriz adjunta de A, ou seja,
a matriz transposta de todos os determinantes cofatores de A.

- Qual seria a matriz inversa de W:

\begin{equation}
    W =
    \begin{bmatrix}
        1 & 4\\
        2 & 5\\
    \end{bmatrix},
\end{equation}

- No `numpy` usamos o método `numpy.linalg.inv`.

## Ajuda

```
import numpy as np
help(np.linalg.inv)
```

**Exemplo** - Encotrar, se existir, a matriz inversa de W.

In [ ]:
W = np.matrix([[1, 4],
              [2, 5]])

np.linalg.inv(W).round(2)

array([[-1.67,  1.33],
       [ 0.67, -0.33]])

In [ ]:
# Vamos demonstrar a definição que a multiplicação de A por sua inversa ser igual a matriz identidade

# Multiply matrix and its inverse
W @ np.linalg.inv(W)

matrix([[1.00000000e+00, 0.00000000e+00],
        [1.11022302e-16, 1.00000000e+00]])

**Exemplo** - uma matriz quadrada singular.

In [ ]:
A = np.matrix([[1, 4],
              [2, 8]])

# Determinante
np.linalg.det(A)

0.0

In [ ]:
np.linalg.inv(A)

## Autovalores e autovetores

- **Transformações lineares** em álgebra linear são funções lineares que conduzem
vetores de um espaço vetorial para outro espaço vetorial.

- Há **transformações lineares proporcionais** que conduzem vetores entre espaços vetoriais de mesma dimensão $F: R^n \rightarrow R^n$. 

- Nesse grupo temos transformações lineares que projetam vetores de um espaço de origem para outro espaço de destino como múltiplos deles mesmo (autovetores),
onde os parâmetros múltiplicadores são conhecidos como $\lambda$ (autovalores):

$$ F: R^n \rightarrow R^n: F(v) = \lambda v \rightarrow  A v = \lambda v$$

A é uma matriz quadrada, $\lambda$ contêm os autovalores e $v$ autovetores representativos.

- A transformação linear sempre vai envolver uma matriz quadrada A, de modo que podemos resolvê-la para qualquer matriz quadrada.

No `numpy` usamos o método `numpy.linalg.eig`

**Exemplos** - calcular os autovalores e autovetores associados a matriz quadrada A.

In [ ]:
# Matriz
A = np.array([[1, -1, 3],
              [1, 1, 6],
              [3, 8, 9]])
A


array([[ 1, -1,  3],
       [ 1,  1,  6],
       [ 3,  8,  9]])

In [ ]:
# Calculando e desconstruindo o resultado para duas variáveis
autovalor, autovetor = np.linalg.eig(A)

In [ ]:
autovalor

array([13.55075847,  0.74003145, -3.29078992])

In [ ]:
autovetor

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

<a name='exerc'></a>
# Exercício 3

## Solução de sistemas de equações lineares

Resolva o seguinte sistema de equação 2 x 2 no Python a partir da álgebra linear para matrizes quadradas.

\begin{equation}
\left\{
\begin{array}{r}
2x-5y=11\\
3x+6y=3
\end{array}
\right.
\end{equation}

\begin{equation}
    A =
    \begin{bmatrix}
    2 & -5\\
    3 & 6\\
    \end{bmatrix}
    \qquad    b =
    \begin{bmatrix}
    11\\
    3\\
    \end{bmatrix}
    \qquad    x =
    \begin{bmatrix}
    x\\
    y\\
    \end{bmatrix}
\end{equation}

### Forma matricial

$$ Ax = b  $$

#### Solução por inversão de matriz

$$x = A^{-1}b$$


In [ ]:
A = np.array([[2, -5],
              [3, 6]])
# Na forma coluna
b = np.array([[11],
              [3]])
print(f'Matriz A\n {A}\n')

Matriz A
 [[ 2 -5]
 [ 3  6]]



In [ ]:
print(f'Matriz b\n {b}')

Matriz b
 [[11]
 [ 3]]


In [ ]:
# Matriz inversa de A
A_inv = np.linalg.inv(A)
A_inv


array([[ 0.22222222,  0.18518519],
       [-0.11111111,  0.07407407]])

**Solução** 

In [ ]:
# Resolução
x = A_inv @ b
print(f'x={float(x[0]):.2f} e y={float(x[1]):.2f}')

x=3.00 e y=-1.00


# Exercícios

## Matriz Insumo-Produto

**Demanda intermediária**

|Vendas/Despesas | Setor 1 | Setor 2 | Subtotal|
|---|---|---|---|
|Setor 1| 20 | 90 | 110|
|Setor 2| 40 | 180 | 220 |
|Subtotal| 60 | 270 | 330|

Dado que os valores brutos da produção dos setores 1 e 2 são, respectivamente, 200 e 600, e que as demandas finais são 90 e 380, encontre os multiplicadores setoriais.


## Referências

- Chen (2018). *Pandas for everyone: python data analysis* Addison-Wesley Professional.
- Marcondes (2018). *Matemática com Python*. São Paulo: Novatec.
- Menezes (2019). *Introdução à programação com Python*. 3 ed. São Paulo: Novatec.
- http://cs231n.github.io/python-numpy-tutorial/
- https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html
- http://www.ie.ufrj.br/intranet/ie/userintranet/hpp/arquivos/matriz_insumo_pruduto_resumo.pdf

