# Programação e Análise de Dados com Python
##### Programa de Pós-Graduação em Economia - PPGE

## Python - Vetores e Matrizes

###### Prof. Hilton Ramalho
###### Prof. Aléssio Almeida

## Objetivo
Desenvolver operações básicas de vetores e matriz no `Python`.


## Conteúdo
1. [Definição](#intro)
2. [Entrada de Matrizes](#matrix)
3. [Operações básicas em matrizes](#operacoes)
4. [Estatísticas básicas](#stats)
5. [Reshape](#reshape)
6. [Operações de álgebra linear](#linalg)
7. [Gerador de Valores Aleatórios](#random)



<a name='intro'></a>

- A biblioteca `numpy` possui uma série de funcões específicas para vetores e matrizes.

## Vetor (Array 1-D)

- No Python, um vetor é representado por uma **array de uma dimensão (Array 1-D)**

- Um vetor pode ser definido como uma coleção de números com comprimento, sentido e direção.

- Vamos escrever o seguinte vetor linha:
\begin{equation}
A=
\begin{bmatrix}
    1 & 2 & 3\\
\end{bmatrix}
\end{equation}

- Vamos escrever o seguinte vetor coluna:
\begin{equation}
A=
\begin{bmatrix}
    1 \\ 2 \\ 3 \\
\end{bmatrix}
\end{equation}

## Matriz (Array 2-D)

- No Python, um vetor é representado por uma **array de duas dimensões (Array 2-D)**

- Normalmente, usamos o termo **matriz** quando há mais de uma dimensão: espaço-linha e o espaço-coluna.

- Matrizes são **arranjos vetores** em dois espaços (linha/coluna) com diversas aplicações em matemática, estatística, econometria...



\begin{equation}
A=
\begin{bmatrix}
    x_{11}       & x_{12} & x_{13} & \dots & x_{1m} \\
    x_{21}       & x_{22} & x_{23} & \dots & x_{2m} \\
    \vdots & \vdots & \vdots & \ddots & \vdots\\
    x_{n1}       & x_{n2} & x_{n3} & \dots & x_{nm}\\
\end{bmatrix}
\end{equation}


## Array 3-D

- Uma Array de três dimensões (3-D) faz um arranjo de matrizes de mesmas dimensões (empilhamento de matrizes).

- Arrays 3-D são **arranjos matrizes**.

![](https://miro.medium.com/max/724/1*X0Dg7QfSYtWhSAu-afi8-g.png)

## Especificações `numpy` de vetores e matrizes

- Toda matriz deve estar contida entre `[]` e depois entre `()`, i.e., `matrix([...])`
- Cada linha é formada por uma lista
- Todo vetor linha ou coluna pode ser escrito usando **o método** `array(...)`. Caso queiramos gerar uma matriz usamos e mesmo método: `array([...])`
- Todo array é da classe `ndarray`.


## Documentação do pacote `numpy`

- [https://numpy.org/doc/](https://numpy.org/doc/)

## Instalação do pacote `numpy`

```
 pip install numpy
```

## Importação da biblioteca ou pacote `numpy`

- Importação é feita com um apelido no intuito de simplicar as chamadas dos
  métodos.

```
import numpy as np
```

## Ajuda

Verificar todos os detalhes do pacote:

```
import numpy
help(numpy)
```

In [ ]:
# Instalação do pacote numpy no NoteBook Colab
!pip install numpy

#### Carregando o pacote `numpy` e ajuda

In [ ]:
# Carregando a biblioteca atribuindo um apelido
import numpy as np
# Ajuda
help(np)

#### Arrays como uma generalização de vetores e matrizes

- Uma array 3-D é uma coleção de matrizes. Por sua vez, uma matriz (Array 2-D) é uma coleção de vetores. Um vetor (Array 1-D) é um coleção de números.
- Portanto, em última análise, usamos o conceito de `array` no `numpy` para representar vetores e matrizes.

**Exemplo** - Carregando o pacote `numpy` e criando um vetor-linha. 
- No `numpy`, por padrão, um vetor será armazendo na forma de matriz-linha.
- Usaremos o método `array`. Ele espera listas como argumento.

### Vetores (Array 1-D)

- Usamos o método `.array` para criar arrays multidimensionais.

In [ ]:
# Carregando a biblioteca
import numpy as np

# Criando um vetor-linha - Array 1-D (empilha apenas 1 matriz linha (vetor))
# Usamos o método array - espera listas como argumento.
# Esse vetor equivale a uma matriz de ordem (1 x 3)
v = np.array([1,2,3])
print(v, type(v))

[1 2 3] <class 'numpy.ndarray'>


In [ ]:
# Tipo do objeto - array multidimensional (array 1-D, array 2-D, array 3-D)
type(v)

numpy.ndarray

In [ ]:
v

array([1, 2, 3])

- Por padrão, os vetores criados pelo `numpy` ficam na forma de matriz linha.
- No entanto, podemos escrever o seguinte vetor na forma de matriz coluna:
- Para numpy você deve escrever uma matriz 3 x 1 (três linhas/ 1 coluna)
\begin{equation}
B=
\begin{bmatrix}
    1\\
    2\\
    3\\
\end{bmatrix}
\end{equation}

In [ ]:
# Criar um vetor na forma matrix-coluna
# Vetor (1,2,3) - forma tupla
# Passar para forma matriz - coluna
u = np.array( [ [1], [2], [3]  ]  )
print(u, type(u))

[[1]
 [2]
 [3]] <class 'numpy.ndarray'>


#### Usando o método reshape para transpor um vetor-linha

In [ ]:
# Criando uma array 1D - vetor linha
v = np.array( [1, 2, 3]  )
v

array([1, 2, 3])

In [ ]:
# Passar um vetor-linha e tem seguida transpor para a forma vetor-coluna
u = v.reshape(3,1)
u

array([[1],
       [2],
       [3]])

#### Propriedades de uma Array 1-D

In [ ]:
# Vamos criar o vetor-linha (array)
v = np.array( [4,-2,0,1,6] )
print(v, type(v))

[ 4 -2  0  1  6] <class 'numpy.ndarray'>


In [ ]:
# Checando algumas propriedades de uma array
# Formato
v.shape

(5,)

In [ ]:
# Dimensão da array (total de objetos)
v.ndim

1

In [ ]:
# Total de elementos dos objetos
v.size

5

In [ ]:
# Tipagem dos elementos
v.dtype

dtype('int64')

In [ ]:
# Cirar uma array 1-D com coleção de números float
u = np.array( [0.5, -2.3, 2.3, 5.6])
u

array([ 0.5, -2.3,  2.3,  5.6])

In [ ]:
# Tipagem os elementos da array
u.dtype

dtype('float64')

In [ ]:
# Propriedades básicas
print(f"Formato da array: {u.shape}. Total de elementos da array: {u.size}. Dimensão da array: {u.ndim}")

Formato da array: (4,). Total de elementos da array: 4. Dimensão da array: 1


#### Ajuda - visão geral dos métodos para arrays

In [ ]:
help(np.array)

## Consulta e Fatiamento de vetores - Array 1-D

- Podemos acessar os elementos de um vetor de forma similar ao que fizemos
  para acessar elementos de um objeto lista no Python, ou seja, usando 
  a indexação para frente e para trás.

In [ ]:
# A função range - permite criar listas de números
list(range(6))

[0, 1, 2, 3, 4, 5]

In [ ]:
# A função range - permite criar listas de números
list(range(10, 30, 2))

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [ ]:
# A função range - permite criar listas de números
list(range(35, 0, -5))

[35, 30, 25, 20, 15, 10, 5]

In [ ]:
list(range(7,0,-1))

[7, 6, 5, 4, 3, 2, 1]

In [ ]:
# Criando um vetor-linha - usando a função range
x = np.array( range(7,0,-1) )
x

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
x[0] # primeiro elemento do vetor

7

In [ ]:
x[-1] # última elemento do vetor

1

In [ ]:
x[-2]  # penúltimo elemento

2

In [ ]:
# Indexação com o operator intervalar
# Todos os elementos
x[:]

array([7, 6, 5, 4, 3, 2, 1])

In [ ]:
# Todos os elementos antes do 3º elemento. [ : <indexador>]
x[:3]

array([7, 6, 5])

In [ ]:
# Todos os elementos a partir do 3º elemento na indexação. [<indexador> : ]
x[3:]

array([4, 3, 2, 1])

In [ ]:
# Selecionando o último elemento
x[-1]

1

## Operações básicas com vetores - Arrays 1-D

- Adição elemento por elemento
- Subtração elemento por elemento
- Multiplicação elemento por elemento
- Multiplicação de vetores - retorna um escalar (produto interno) e retorna uma matriz (produto externo)
- Divisão elemento por elemento - retorna um vetor

**Exemplo** - Criando vetores com mesma dimensão.

In [ ]:
# Vetor-linha a
a = np.array([1, 2, 3])
# Vetor-linha b
b = np.array([0, 1, 1])
print(f' a = {a}\n b = {b}. Tipo {type(a)}' )

 a = [1 2 3]
 b = [0 1 1]. Tipo <class 'numpy.ndarray'>


In [ ]:
# Vetores com a mesma dimensão
print(a.size)
print(b.size)

3
3


**Adição** - **Somar dois vetores** - Somamos elemento por elemento e o resultado será um novo vetor. Usamos o operador `+`

In [ ]:
# Adição de elemento por elemento
print(a, b)
c = a + b
c

[1 2 3] [0 1 1]


array([1, 3, 4])

**Subtração de vetores** - subtraimos elemento por elemento e o resultado será um novo vetor. Usamos o operador `-`.

In [ ]:
# Subtração de elemento por elemento
print(a, b)
c = a - b
print(c)

[1 2 3] [0 1 1]
[1 1 2]


**Multiplicação de elementos** - multiplicamos elemento por elemento e o resultado será **um novo vetor**. Usamos o operador `*`.

**Observação** - Não se trata da operação de multiplicação de vetores da álgebra linear e sim uma multiplicação interativa de elemento por elemento.

In [ ]:
# Multiplicação elemento por elemento - resulta será um novo vetor
print(a,b)
c = a * b
c

[1 2 3] [0 1 1]


array([0, 2, 3])

**Divisão de elementos** - multiplicamos elemento por elemento e o resultado será **um novo vetor**. Usamos o operador `/`.


In [ ]:
# Divisão elemento por elemento - resulta será um novo vetor
# Vetor-linha a
a = np.array([1, 2, 3])
# Vetor-linha b
b = np.array([3, 2, 1])
print(a,b)
c = a / b
c

[1 2 3] [3 2 1]


array([0.33333333, 1.        , 3.        ])

#### Produto escalar (interno) de vetores

- Multiplicar vetores de mesma dimensão para produzir um número. 
- vetor-linha x vetor-coluna - vetores com a mesma dimensão
- Usamos o operador `@` para fazer a multiplicação de vetores - produto escalar.

In [ ]:
# Criar os dois vetores-linha
a = np.array( [ 0, -2, 4 ] )
b = np.array( [ 3, 2, 2 ] )
print(a, b)

[ 0 -2  4] [3 2 2]


In [ ]:
# Produto interno (escalar)
a @ b

4

In [ ]:
# Produto interno (escalar)
b @ a

4

#### Usando o método `.dot`

- Podemos usar o método `.dot` para calcular o produto interno entre dois vetores.

In [ ]:
# Criando os vetores
a = np.array( [ 0, -2, 4 ] )
b = np.array( [ 3, 2, 2 ] )

# Produto escalar
np.dot(a,b)

4

In [ ]:
np.dot(b,a)

4

#### Produto externo de vetores - resultado matriz

- Multiplicar vetores de mesma dimensão para produzir uma matriz. 
- vetor-coluna x vetor-linha
- Usamos o método `array.reshape`

In [ ]:
# Criando os vetores
a = np.array( [ 5, -1, 1 ] )
b = np.array( [ 8, 0, 1 ] )

In [ ]:
# array a
a

array([ 5, -1,  1])

In [ ]:
# array b
b

array([8, 0, 1])

In [ ]:
a.reshape(3,1)

array([[ 5],
       [-1],
       [ 1]])

In [ ]:
# Gerando uma matriz 3x3 - ao multiplcar uma matriz 3 x 1 por uma matriz 1 x 3
a.reshape(3,1) @ b.reshape(1,3)


array([[40,  0,  5],
       [-8,  0, -1],
       [ 8,  0,  1]])

<a name='matrix'></a>
# Matrizes - Array 2-D

- Uma matriz é um objeto bi-dimensional a partir de dois espaços vetoriais: espaço-linha e espaço-coluna.

- Vamos escrever a seguinte matriz:
\begin{equation}
A=
\begin{bmatrix}
    1 & 2 & 3\\
    4 & 5 & 6 \\
    7 & 8 & 9\\
\end{bmatrix}
\end{equation}

## Sintaxe dos métodos 

- Podemos criar matrizes no `numpy` a partir de dois métodos: 
- O método `.array` e o método `.matrix`.
- Observe a sintaxe de construção do objeto onde passamos uma lista
  aninhada, onde cada lista filha é um vetor linha da matriz.
```
np.array( [ [ vetor linha 1 ], [ vetor linha 2], ..., [vetor linha n] ] )
np.matrix( [ [ vetor linha 1 ], [ vetor linha 2], ..., [vetor linha n]] )
```

Observe que os **vetores linhas devem possuir o mesmo número de elementos** para a formação do espaço-coluna da matriz.

## Ajuda

```
import numpy as np
help(np.array)
help(np.matrix)
```

**Exemplo** - Criando uma matriz com o método `.matrix`.

In [ ]:
# Empilhando vetores no espaço-linha - usando o método matrix
# Vamos criar três listas
v1 = [1,2,3]
v2 = [4,5,6]
v3 = [7,8,9]

# Criando uma matriz de ordem 3 x 3
np.matrix([ v1, v2, v3 ])

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

**Exemplo** - Criando uma matriz (Array 2-D - espaço-linha/espaço-coluna) com o método `.array`.

In [ ]:
# Criando matriz usando o método array - matrix 3 x 3 
a = np.array([ [1,2,3], [4,5,6], [7,8,9]  ])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Criando matriz usando o método array - matrix 3 x 2
a = np.array([ [3,4], [-2,-1], [0,1]  ])
a

array([[ 3,  4],
       [-2, -1],
       [ 0,  1]])

In [ ]:
# Total de elementos da matriz
a.size

6

In [ ]:
# Dimensão da matriz
a.shape

(3, 2)

In [ ]:
# Dimensão da array
a.ndim

2

In [ ]:
# Criando matriz usando o método array - matrix 2 x 3 - Array 2-D
a = np.array([ [-1,0,0], [5,7,10] ])
a

array([[-1,  0,  0],
       [ 5,  7, 10]])

In [ ]:
# Formato da array
a.shape

(2, 3)

In [ ]:
# Criando matriz usando o método array - matrix 2 x 2
a = np.array([ [3,4], [0,1] ])
a

array([[3, 4],
       [0, 1]])

In [ ]:
a.shape

(2, 2)

**Exemplo** - **Transformando listas em Array** - Criando uma matriz a partir do empilhamento de listas de mesma dimensão nas linhas da matriz. Usamos o método `.asarray`. Veja a ajuda:
```
import numpy as np
help(no.asarray)
```

In [ ]:
# Imagine o caso em que temos vetores - .asarray - empilhar lista para uma array (matriz)
a = [1,2,3]
b = [4,5,6]
c = [7,8,9]
# Empilhando
mat_a = np.asarray([a,b,c])
mat_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Consulta e Fatiamento de matrizes

- Lógica de indexação de arrays/matrizes segue a mesma indexação de lista aninhadas (agrupadas)

```
[  [ vetor-linha1  ], [ vetor linha2]      ]
```
- vetor-linha1 - ocupa a posição 0 na lista principal
- vetor linha2 - ocupa a posição 1 na lista principal

- Se vetor-linha1 = [2,3,4], o elemento 3 ocupa a posição 1 nesta lista
- Se vetor-linha2 = [0,5,1], o elemento 1 ocupa a posição 2 nesta lista

```
[  [2,3,4], [0,5,1]  ]
```

Então, se a matriz (2 x 3) é dada por:
```
A = np.array( [ [2,3,4], [0,5,1] ] )
```

Na matemática queremos acessar, por exemplo, o elemento de A da linha 1 e coluna 2, ou seja, 3.
No `numpy` ele está indexado por:

A linha 1 - ela ocupa a posição 0 na lista principal que forma a array/matriz:
```
A[0,...]
```
Por outro lado, o elemento 3 da lista [2,3,4] ocupa a posição 1 nesta lista. Portanto:
```
A[0,1]
```
Equivale a acessar o elemento da matriz A da linha 1/coluna 2, que no `numpy`
equivale ao elemento indexado por [0,1]




**Exemplo** - Acessando o elemento A[1,1] da matriz A. Na indexão do Python equivale a acessar a linha de posição 0 e o elemento desta linha que ocupa a posição 0:

In [ ]:
# Criamos a array (matrix 2 x 3)
a = np.array( [ [2,3,4], [0,5,1] ] )
a


array([[2, 3, 4],
       [0, 5, 1]])

In [ ]:
# Selecionando a primeira linha da matriz
a[0]

array([2, 3, 4])

In [ ]:
# Selecionando a primeira linha da matriz
a[1]

array([0, 5, 1])

In [ ]:
print(a)
# Todos as linhas antes da linha da posição 1
a[:1]

[[2 3 4]
 [0 5 1]]


array([[2, 3, 4]])

In [ ]:
# Acessar o elemento a11 - elemento na primeira linha e na primeira coluna
print(a)
# 1 - selecione a linha da posição 0. 2 - nesta linha, selecione o elemento da posição 0
a[0,0]

[[2 3 4]
 [0 5 1]]


2

In [ ]:
# Acessar o elemento a12 - elemento na primeira linha e na segunda coluna
print(a)
# 1 - selecione a linha da posição 0. 2 - nesta linha, selecione o elemento da posição 0
a[0,1]

[[2 3 4]
 [0 5 1]]


3

In [ ]:
# Acessar o elemento a23 - elemento na segunda linha e na terceira coluna
print(a)
# 1 - selecione a linha da posição 0. 2 - nesta linha, selecione o elemento da posição 0
a[1,2]

[[2 3 4]
 [0 5 1]]


1

In [ ]:
# Selecionar a última linha - indexação negativa
a[-1]

array([0, 5, 1])

In [ ]:
# Selecionar a primeira linha
a[0]

array([2, 3, 4])

In [ ]:
# Matriz 2 x 2

# Operador de seleção intervalar :
# :1 - Todas as linhas anteriores a linha de posição 1
# Em seguida, acessamos 0:2 - os elementos desta linha a partir da posição 0
# e antes da posição 2
print(a)
a[:1,0:2]

[[2 3 4]
 [0 5 1]]


array([[2, 3]])

In [ ]:
# Matriz 2 x 2

# Operador de seleção intervalar :
# :1 - Todas as linhas anteriores a linha de posição 1
# Em seguida, acessamos 0: - os elementos desta linha a partir da posição 0
print(a)
a[:1,0:]

[[2 3 4]
 [0 5 1]]


array([[2, 3, 4]])

In [ ]:
# Matriz 2 x 3
# Criamos a array (matrix 3 x 3)
a = np.array( [ [2,3,4], [0,5,1], [1,1,1] ] )
# Operador de seleção intervalar :
# :2 - Todas as linhas anteriores a linha de posição 2
# Em seguida, acessamos :2 - em cada linha, selecionamos os elementos anteriores
# a posição 2
print(a)
a[:2,:2]

[[2 3 4]
 [0 5 1]
 [1 1 1]]


array([[2, 3],
       [0, 5]])

In [ ]:
# Duas primeiras linhas e todas as colunas da matriz
# :2 - Todos os elementos-linha antes da linha de posição 2
# : - Todas as colunas
a[:2,:]

array([[2, 3, 4],
       [0, 5, 1]])

In [ ]:
# Todas as linhas e a segunda coluna
a[:,1]

array([3, 5])

## Descrevendo uma matriz

- Podemos descrever propriedades de uma matriz/vetor:
- Formato da matriz/vetor com o método `.shape`
- Total de elementos da matriz/vetor com método `.size`
- Dimensão da matriz/vetor com o método `.dim`

- Todos eles são submétodos de um objeto `numpy array`.

**Exemplo** - Criando uma matriz com o método `.array`.

In [ ]:
# Vamos criar a matriz A (3 x 3)
a = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

**Exemplo** - Verificando o formato da matriz.

In [ ]:
a.shape

(3, 3)

**Exemplo** - Verificando o total de elementos da matriz.

In [ ]:
# Número de elementos = número linhas * número de colunas
a.size

9

**Exemplo** - Verificando a dimensão da matriz (espaço-linha e espaço-coluna)

In [ ]:
# Número de dimensões - espaço linha e o espaço coluna
a.ndim

2

### Matrizes especiais

Na família de matrizes temos um conjunto de matrizes especiais que podem ser usadas para facilitar várias tarefas de programação envolvendo álgebra linear.

- Matriz nula - todos os elementos iguais a zero.
- Matriz identidade (quadrada) - matriz quadrada (diagonal) com todos os elementos da diagonal principal iguais a 1 e os demais iguais a zero.
- Matriz com elementos repetidos - matriz cujos elementos são todos iguais

**Exemplo** - criando matrizes nulas - método `.zeros`.

```
import numpy as np
help(np.zeros)
```


#### Método `.zeros`

-  Criar uma matriz nula com `n` elementos. - `np.zeros(4)`

In [ ]:
# Vetor linha - array 1-D
np.array([0,0,0,0,0,0])

array([0, 0, 0, 0, 0, 0])

In [ ]:
# Vetor linha nulo
v = np.zeros(6)
print(v)

[0. 0. 0. 0. 0. 0.]


In [ ]:
# Vetor nulo
v = np.zeros(2)
print(v)

[0. 0.]


In [ ]:
# Vetor nulo com elementos inteiros
v = np.zeros(6, dtype='int')
print(v)

[0 0 0 0 0 0]


In [ ]:
# Vetor nulo
v = np.zeros(2, 'int')
print(v)

[0 0]


#### Método `.zero`

- Para criar uma matriz, passamos uma tupla como argumento - (número de linhas, número de colunas)

In [ ]:
# Matriz com valores zerados - método zeros
# passamos o shape como uma tupla (total de linhas, total de colunas)
v = np.zeros((4,3))
v

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.array( [ [0,0,0], [0,0,0], [0,0,0], [0,0,0]])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
# Matriz com valores zerados - método zeros
# passamos o shape como uma tupla (total de linhas, total de colunas)
v = np.zeros((2,5), 'int')
v

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
# Matriz com valores zerados - método zeros
# passamos o shape como uma tupla (total de linhas, total de colunas)
v = np.zeros((4,4), 'int')
v

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

**Exemplo** - Criando uma matriz com elementos repetidos e iguais a 1. Usamos o método `.ones`. 

```
import numpy as np
help(np.ones)

```

In [ ]:
v = np.ones(4)
v

array([1., 1., 1., 1.])

In [ ]:
# Matriz com valores 1 - método ones
v = np.ones((4,3))
v

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [ ]:
# Matriz quadrada
np.ones((2,2), 'int')

array([[1, 1],
       [1, 1]])

In [ ]:
# Vetor - array 1-D
np.ones(10, 'int')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

**Exemplo** - Criando uma matriz com elementos repetidos e iguais. Usamos o método `ones` seguido por multiplação da matriz por um escalar.

In [ ]:
# Matriz com valores repetidos - criarmos a matriz com elementos = 1 e 
# Multiplicamos essa matriz por um escalar
np.ones((4,3), 'int')*5

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# Matriz com valores repetidos - criarmos a matriz com elementos = 1 e 
# Multiplicamos essa matriz por um escalar
np.ones((3,3), 'int')*-2

array([[-2, -2, -2],
       [-2, -2, -2],
       [-2, -2, -2]])

## Matriz identidade

- Para a criação de uma matriz identidade usamos o método `.identity`.

## Ajuda

```
import numpy as np
help(np.identity)
```

**Exemplo** - Criando uma matriz identidade 2 x 2

In [ ]:
# Criar uma matriz identidade 1 x 1
a = np.identity(1)
print(a)

[[1.]]


In [ ]:
# Criar uma matriz identidade 2 x 2
a = np.identity(2, dtype='int')
print(a)

[[1 0]
 [0 1]]


**Exemplo** - Criando uma matriz identidade com elementos números inteiros.

In [ ]:
# Criar uma matriz identidade 2 x 2 - elementos inteiros
a = np.identity(3, 'int')
print(a)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [ ]:
# Matriz identidade - método identity
a = np.identity(10, 'int')
a

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

**Exemplo** - Criando uma matriz diagonal a partir de uma matriz identidade multiplicada por um escalar.

In [ ]:
# Matriz diagonal - matriz identidade vezes um escalar
d = np.identity(5)*5
print(d)

[[5. 0. 0. 0. 0.]
 [0. 5. 0. 0. 0.]
 [0. 0. 5. 0. 0.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


<a name='operacoes'></a>
# Operações com os elementos de matrizes

- Soma (adição/subtração) de matrizes de mesmo formato - elemento por elemento
- Multiplicação de elementos de matrizes de mesmo formato - elemento por elemento.
- Multiplicação de matrizes A x B - espaço-coluna de A = espaço-linha de B
- Divisão de elementos de matriz de mesmo formato - elemento por elemento



**Exemplo** - Criando uma matriz.

In [ ]:
# Criar uma matriz 3 x 3
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Exemplo** - Soma de cada elemento com um escalar. Usamos o operador `+`

In [ ]:
# Somar 100 a todos os elementos da matriz
a + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

**Exemplo** - Subtração de cada elemento com um escalar. Usamos o operador `-`.

In [ ]:
# Subtrair 100 a todos os elementos da matriz
a - 10

array([[-9, -8, -7],
       [-6, -5, -4],
       [-3, -2, -1]])

**Exemplo** - multiplicação de cada elemento com um escalar. . Usamos o operador `*`.

In [ ]:
# Multiplicar por 10 todos os elementos da matriz
a * 10

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

**Exemplo** - Divisão de cada elemento com um escalar. Usamos o operador `/`.

In [ ]:
# Dividir por 10 todos os elementos da matriz
a / 10

array([[0.1, 0.2, 0.3],
       [0.4, 0.5, 0.6],
       [0.7, 0.8, 0.9]])

**Exemplo** - Potência de cada elemento com um escalar. Usamos o operador `**`.

In [ ]:
# Potencializar por 2 todos os elementos da matriz
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

**Exemplo** - Criamos duas matrizes.

In [ ]:
# Matrizes 2 x 2
a = np.array([ [1,2], [0,1] ])
b = np.array([ [9,2], [0,-1] ])   

[[1 2]
 [0 1]] [[ 9  2]
 [ 0 -1]]


In [ ]:
print(a, a.shape)

[[1 2]
 [0 1]] (2, 2)


In [ ]:
print(b, b.shape)

[[ 9  2]
 [ 0 -1]] (2, 2)


**Exemplo** - Soma de duas matrizes de mesma dimensão.

In [ ]:
# Adição
print(a)
print(b)
a + b

[[1 2]
 [0 1]]
[[ 9  2]
 [ 0 -1]]


array([[10,  4],
       [ 0,  0]])

**Exemplo** - Subtração de duas matrizes de mesma dimensão.

In [ ]:
# Subtração
print(a)
print(b)
a - b

[[1 2]
 [0 1]]
[[ 9  2]
 [ 0 -1]]


array([[-8,  0],
       [ 0,  2]])

**Exemplo** - Multiplicação elemento por elemento de matrizes mesma dimensão no espaço linha e coluna (mesmo formato).

In [ ]:
# Multiplicação elemento por elemento
# Matrizes 3 x 2 - mesmo shape
a = np.array([ [1,2], [0,1], [3,1] ])
b = np.array([ [9,2], [0,-1], [2,1] ]) 

print(a, a.shape)
print(b, b.shape)

# Multiplicação elemento por elemento
a * b

[[1 2]
 [0 1]
 [3 1]] (3, 2)
[[ 9  2]
 [ 0 -1]
 [ 2  1]] (3, 2)


array([[ 9,  4],
       [ 0, -1],
       [ 6,  1]])

In [ ]:
# Multiplicação elemento por elemento
b * a

array([[ 9,  4],
       [ 0, -1],
       [ 6,  1]])

## Multiplicação de matrizes 

- Para a multiplicação de objetos que são matrizes usamos  o método `.matmul`.

## Ajuda

```
import numpy as np
help(np.matmul)
```

**Exemplo** - multiplicação de duas matrizes - espaço-linha de A deve ter a mesma dimensão do espaço-coluna de B para as operações de produto interno de vetores.

In [ ]:
# Criamos duas Matrizes 2 x 2 - mesmo shape
a = np.array([ [1,2], [0,1] ])
b = np.array([ [9,2], [0,-1] ]) 
print(a, a.shape)
print(b, b.shape)

[[1 2]
 [0 1]] (2, 2)
[[ 9  2]
 [ 0 -1]] (2, 2)


In [ ]:
# Multiplicação de matrizes-  A (2x2) * B(2x2)
np.matmul(a,b)

array([[ 9,  0],
       [ 0, -1]])

In [ ]:
np.matmul(b,a)

array([[ 9, 20],
       [ 0, -1]])

In [ ]:
# Criamos duas Matrizes - uma matriz A 2 x 3 e outra B 3 x 2
a = np.array([ [1,2,4], [0,1,0] ])
b = np.array([ [9,2], [0,-1], [1,-1] ]) 
print(a, a.shape)
print(b, b.shape)

[[1 2 4]
 [0 1 0]] (2, 3)
[[ 9  2]
 [ 0 -1]
 [ 1 -1]] (3, 2)


In [ ]:
# A2x3 * B3x2 = C2x2
np.matmul(a,b)

array([[13, -4],
       [ 0, -1]])

In [ ]:
# B3x2 * A2x3 = C3x3
np.matmul(b,a)

array([[ 9, 20, 36],
       [ 0, -1,  0],
       [ 1,  1,  4]])

In [ ]:
# Criamos duas Matrizes - uma matriz A 2 x 2 e outra B 2 x 3
a = np.array([ [1,2], [0,1] ])
b = np.array([ [9,2,1], [0,-1,2] ]) 
print(a, a.shape)
print(b, b.shape)

[[1 2]
 [0 1]] (2, 2)
[[ 9  2  1]
 [ 0 -1  2]] (2, 3)


In [ ]:
# Multiplicar
np.matmul(a,b)

array([[ 9,  0,  5],
       [ 0, -1,  2]])

In [ ]:
# Multiplicar sem conformidade
np.matmul(b,a)

ValueError: ignored

### Multiplicação de matrizes com o operador `@`

-  A @ B - Observar que a multiplicação de duas matrizes requer que **a dimensão do espaço-coluna de A deve ser igual a dimensão do espaço-linha de B**.

In [ ]:
# Multiplicação de matrizes B2x2 * A2x3
b = np.array([ [1,2], [0,1] ])
a = np.array([ [9,2,2], [0,-1,1] ])  
print(a, a.shape)
print(b, b.shape) 
b @ a

[[ 9  2  2]
 [ 0 -1  1]] (2, 3)
[[1 2]
 [0 1]] (2, 2)


array([[ 9,  0,  4],
       [ 0, -1,  1]])

In [ ]:
# Multiplicação não definida
a @ b

ValueError: ignored

## Ordenar valores de uma matriz

- Em algumas situações particulares podemos ordenar os elementos de uma matriz 
conforme uma linha ou coluna.

- Para tanto, usamos o método `.argsort`.

## Ajuda

```
import numpy as np
help(np.argsort)
```

In [ ]:
# Criar uma matriz 3x3
a = np.array([[4, 5, 6],
              [2, 3, 1],
              [7, 8, 9]])
print(a, a.shape)

[[4 5 6]
 [2 3 1]
 [7 8 9]] (3, 3)


In [ ]:
# Seleção/fatiamento intervalar - operador : 
# a[<indexação das linhas> : <indexão das colunas>]

# Acessar/fatiar a primeira linha
print(f"Primeira linha: {a[0,:]}")

# .argsort - ordenar do menor para o maior elemento
# Índices ordenados
print(a[0,:].argsort(axis=0))

Primeira linha: [4 5 6]
[0 1 2]


In [ ]:
# Acessar/fatiar a segunda linha
print(f"Segunda linha: {a[1,:]}")

# .argsort - ordenar do menor para o maior elemento
# Índices ordenados
print(a[1,:].argsort(axis=0))

Segunda linha: [2 3 1]
[2 0 1]


In [ ]:
#Ordenada pelos valores da primeira coluna
indice = a[:,0].argsort(axis=0)
print(indice)

[1 0 2]


In [ ]:
print(a)

# Acessar a primeira coluna
print(a[:,0])

# Ordenar todos os elementos para primeira coluna
indice = a[:,0].argsort(axis=0)

# axis = 0 - ordernar por linha
print(indice)

# Ex: 
# índice ordenador por linha [1 0 2] - do menor valor para o maior
# coluna de referência [4 2 7]

# Ordenar as linhas (passar o índice para o espaço) 
a[indice, :]

[[4 5 6]
 [2 3 1]
 [7 8 9]]
[4 2 7]
[1 0 2]


array([[2, 3, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
print(a)

# Acessar a segunda coluna
print(a[:,1])

# Ordenar todos os elementos por linhas conforme a segunda coluna
indice = a[:,1].argsort(axis=0)
print(indice)

# Ordenar as linhas (passar o índice para o espaço) 
a[indice, :]

[[4 5 6]
 [2 3 1]
 [7 8 9]]
[5 3 8]
[1 0 2]


array([[2, 3, 1],
       [4, 5, 6],
       [7, 8, 9]])

<a name='stats'></a>
# Estatísticas básicas

Podemos calcular estatísticas básicas a partir dos elementos de uma matriz, seja filtrando por linha ou coluna. Para tanto, podemos usar alguns métodos:

- Valor máximo - método `.max`.
- Valor mínimo - método `.min`.
- Média - método `.mean`.
- Média excluíndo dados faltantes - método `.nanmean`.
- Variância - método `.var`.
- Desvio padrão `.std`.
- Soma `.sum`.

- Observe os exemplos abaixo:



In [ ]:
import numpy as np

# Criar uma matrix 3 x 3 - Array 2-D
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Elemento de valor máximo da matriz
np.max(a)

9

In [ ]:
# modo alternativo
a.max()

9

In [ ]:
print(a)

# Por coluna
# Máximo valor de cada coluna da matriz
np.max(a, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([7, 8, 9])

In [ ]:
# Por linha
# Máximo valor de cada linha da matriz
np.max(a, axis=1)

array([3, 6, 9])

In [ ]:
# Forma alternativa
a.max(axis=1)

array([3, 6, 9])

In [ ]:
print(a)
# Valor Mínimo
np.min(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


1

In [ ]:
# Forma alternativa
a.min()

1

In [ ]:
print(a)
# Valor Mínimo por coluna
np.min(a, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([1, 2, 3])

In [ ]:
# Valor Mínimo por linha
np.min(a, axis=1)

array([1, 4, 7])

In [ ]:
# Somatório
print(a)
np.sum(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [ ]:
# Soma de todos os elementos
a.sum()

45

In [ ]:
# Soma por coluna
print(a)
np.sum(a, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([12, 15, 18])

In [ ]:
# Soma por linha
print(a)
np.sum(a, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([ 6, 15, 24])

In [ ]:
print(a)
# Média
np.mean(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


5.0

In [ ]:
# Média por coluna
print(a)
np.mean(a, axis=0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4., 5., 6.])

In [ ]:
# Média por linha
print(a)
np.mean(a, axis=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([2., 5., 8.])

In [ ]:
# Variância
print(a)
np.var(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


6.666666666666667

In [ ]:
# Variância por coluna
print(a)
np.var(a, axis = 0)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([6., 6., 6.])

In [ ]:
# Variância por linha
print(a)
np.var(a, axis = 1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([0.66666667, 0.66666667, 0.66666667])

In [ ]:
# Desvio-padrão
print(a)
np.std(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2.581988897471611

In [ ]:
# Retorna DP por coluna
np.std(a, axis = 0)

array([2.44948974, 2.44948974, 2.44948974])

In [ ]:
# Retorna DP por linha
np.std(a, axis = 1)

array([0.81649658, 0.81649658, 0.81649658])

## Exercício

- Suponha que uma turma possui as seguintes notas:

|Aluno | AV1 | AV2 | AV3|
|---|---|---|---|
|A| 10 | 8 | 7 |
|B| 2 | 9 | 10 |
|C| 4 | 6 | 4 |


- Represente as notas acima em uma matriz `A`, calculando a média e desvio-padrão por aluno e por avaliação. Escreva o resultado em um dicionário.


In [ ]:
# Criamos a matriz de notas
a = np.array([ [10,8,7], [2,9,10], [4,6,4] ])
a

array([[10,  8,  7],
       [ 2,  9, 10],
       [ 4,  6,  4]])

 - Criar um dicionário para guardar os resultados

```
  { "aluno": { "media": <valor>, "dp": <valor> }, 
  "prova": { "media": <valor>, "dp": <valor> } }
```

In [ ]:
# Criar um dicionário - que coleciona dois dicionários
resultado = {
    'aluno': {
        'media': np.mean(a, axis=1), 
        'dp': np.std(a, axis=1)
    },
    'prova': {
        'media': np.mean(a, axis=0), 
        'dp': np.std(a, axis=0)
    }
}
resultado

{'aluno': {'dp': array([1.24721913, 3.55902608, 0.94280904]),
  'media': array([8.33333333, 7.        , 4.66666667])},
 'prova': {'dp': array([3.39934634, 1.24721913, 2.44948974]),
  'media': array([5.33333333, 7.66666667, 7.        ])}}

## Exercício

- Suponha que uma turma possui as seguintes notas:

|Aluno | AV1 | AV2 | AV3|
|---|---|---|---|
|A| 10 | 8 | 7 |
|B| 2 | 9 | 10 |
|C| 4 | 6 | 4 |
|D|0|5|F|


- Represente as notas acima em uma matriz `A`, calculando a média e desvio-padrão por aluno e por avaliação. Trate a falta do aluno D como uma informação faltante.


## Representar um elemento faltante

-  Método `np.nan`.


In [ ]:
a = np.array( [ [10,8,7], [2,9,10], [4,6,4], [0,5, np.nan] ] )
a

array([[10.,  8.,  7.],
       [ 2.,  9., 10.],
       [ 4.,  6.,  4.],
       [ 0.,  5., nan]])

In [ ]:
# Vamos tentar calcular a média por aluno
np.mean(a, axis=1)

array([8.33333333, 7.        , 4.66666667,        nan])

In [ ]:
# Vamor calcular a média por aluno - excluindo o elemento faltante do cálculo
np.nanmean(a, axis=1)


array([8.33333333, 7.        , 4.66666667, 2.5       ])

In [ ]:
# Criar um dicionário - média/dp por aluno e média/pd por turma
resultado = {
    'aluno':{
        'media': np.nanmean(a, axis=1), 'dp': np.nanstd(a, axis=1)
        },
        'prova': {
            'media': np.nanmean(a, axis=0), 'dp': np.nanstd(a, axis=0)
        }
             }
resultado

{'aluno': {'dp': array([1.24721913, 3.55902608, 0.94280904, 2.5       ]),
  'media': array([8.33333333, 7.        , 4.66666667, 2.5       ])},
 'prova': {'dp': array([3.74165739, 1.58113883, 2.44948974]),
  'media': array([4., 7., 7.])}}

In [ ]:
av1=resultado['prova']['media'][0]
av2=resultado['prova']['media'][1]
av3=resultado['prova']['media'][2]
print(f'''
Médias da Turma
-------------------
1ª Avaliação: {av1}
2ª Avaliação: {av2}
3ª Avaliação: {av3}
''')


Médias da Turma
-------------------
1ª Avaliação: 4.0
2ª Avaliação: 7.0
3ª Avaliação: 7.0



<a name='reshape'></a>
# Reshape Vetores e Matrizes

- O `reshape` permite reestruturar uma matriz para mantermos os mesmos dados, mas com uma nova organização de linhas e colunas.

- O único requisito é que o formato da matriz original e da nova contenha o mesmo número de elementos.


In [ ]:
# Criando um vetor - Array 1-D
import numpy as np
a = np.array( range(0,12) )
print(a)

print(a.shape, a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
(12,) 1


In [ ]:
# Usar o reshape para transpor a matriz-linha para uma matriz-coluna
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

#### Transformando um vetor em matriz

-  Distribuindo os elementos com o método `.reshape`

In [ ]:
# Vetor A - Array 1-d
print(a, a.shape, a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,) 1


**Exemplo** - usamos o método `.reshape` para transformar um vetor em uma matriz distribuindo os elementos sequenciamente por linhas.

In [ ]:
# Reshape 2x6 - Array 2-D
b = a.reshape(2, 6)
print(b, b.shape, b.ndim)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] (2, 6) 2


**Exemplo** - usamos o método `.reshape` para transformar uma matriz outra matriz distribuindo os elementos sequenciamente por linhas conforme o formato desejado.

In [ ]:
# Vetor
print(a)

# Transformando em uma matriz
b = a.reshape(3,4)
b

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

#### Transformando um Array 2-D em um Array 1-D
**Exemplo** - usamos o método `.reshape` para transformar uma matriz em vetor distribuindo os elementos sequenciamente.

In [ ]:
# Matriz B (3,4) - Array 2-D
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Transformar uma matriz B em uma matriz de única dimensão (vetor)
# o valor -1 garante a mundança de todos os elementos
# reshape ( "uma linha", -1 = distribuição de todos os elementos em várias colunas)

# Conversão para uma matriz-linha 2-D
c = b.reshape(1, -1)

print(c, c.shape, c.ndim)

[[ 0  1  2  3  4  5  6  7  8  9 10 11]] (1, 12) 2


In [ ]:
# Array 1-D
a = np.array( range(0, 12) )
print(a, a.shape, a.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,) 1


**Exemplo** - **Transformação efetiva de uma Array 1-D para um Array 2-D** usamos o método `.flatten` para transformar um vetor em uma matriz distribuindo os elementos sequenciamento por linhas. Usaremos o método `.flatten()`

In [ ]:
# Matriz (3,4) - Array 2-D
print(b, b.shape, b.ndim)

# Transformar Array 2-D forma de tornar a matriz em 1-D
c = b.flatten()

print(c, c.shape, c.ndim)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] (3, 4) 2
[ 0  1  2  3  4  5  6  7  8  9 10 11] (12,) 1


## Matriz Transposta

- A transposição é uma operação comum em álgebra linear na qual os índices de coluna e linha de cada elemento são trocados. Ou seja, alteramos as dimensões dos espaços linha e coluna.

- No Python usamos o método `.T` para efetuar essa operação.



In [ ]:
# Matriz (3,4) - Array 2-D
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11,12]])
print(a, a.shape, a.ndim)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2


In [ ]:
# Transposta
b = a.T
b

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
print(a.shape, b.shape)

(3, 4) (4, 3)


**Observação** - o método `.reshape` não faz a transposição de matrizes. Ele apenas redistribui os elementos para um novo arranjo.

In [ ]:
# Redistribuindo
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
# Matriz transposta
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])


- OBS: tecnicamente, um vetor não pode ser transposto porque é apenas uma coleção de valores.


In [ ]:
# Vetor transposto! Array 1-D
a = np.array([1, 2, 3, 4, 5, 6])
print(a, a.shape, a.ndim)

[1 2 3 4 5 6] (6,) 1


In [ ]:
# Transpor uma array 1-D
a.T

array([1, 2, 3, 4, 5, 6])

In [ ]:
# Criar uma Array 2-D como uma matrix-linha (1, 6)
a = np.array( [ [1, 2, 3, 4, 5, 6]  ]  )
print(a, a.shape, a.ndim)

[[1 2 3 4 5 6]] (1, 6) 2


In [ ]:
# Transpondo para matriz coluna (6,1)
a.T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

<a name='linalg'></a>
# Operações de álgebra linear

## Posto matricial - Arrays 2-D (Matrizes)

- O posto (rank) de uma matriz é o **número de linhas não-nulas da matriz** quando transformada na forma escalonada por linhas.

- Equivalentemente, corresponde ao número de linhas ou colunas linearmente independentes da matriz.

- O posto tem implicações em relação à independência linear e a dimensão de um espaço vetorial.

- NumPy possui uma função *linear algebra*: `np.linalg.matrix_rank( )`

$$rank(A_{n,m})\leq \min(n,m)$$

## Ajuda

```
import numpy as np
help(np.linalg)
```



In [ ]:
help(np.linalg) 

**Exemplo** - calculando o posto da matriz A

In [ ]:
# Criamos a matriz A (2,2)
a = np.array([[1, 2], [2, 4]])
a

array([[1, 2],
       [2, 4]])

In [ ]:
# Calcular o posto da matriz escalonada
np.linalg.matrix_rank(a)

1

## Eliminação Gaussiana
- Por que A tem duas linhas não nulas e o posto é 1 ?
- O posto é o total de linhas não nulas da matriz escalonada


**Exemplo** 

- Criamos uma **matriz elementar** que opera a troca: L2 <-> L2 - 2L1 seguindo as propriedades teóricas da eliminação Gaussiana. 

- Multiplicamos a matriz A por essa matriz elementar para efetuar uma rodade de escalonado. Só uma rodada será suficiente para nosso exemplo.


Vide (https://en.wikipedia.org/wiki/Gaussian_elimination)[https://en.wikipedia.org/wiki/Gaussian_elimination]


In [ ]:
# Matriz elementar de operação gaussiana
e1 = np.array([[1,0],[-2,1]])
e1

array([[ 1,  0],
       [-2,  1]])

In [ ]:
# Reduzir A para a forma escalonada - observe o número de linhas não nulas
a_gauss = np.matmul(e1, a)
a_gauss

array([[1, 2],
       [0, 0]])

**Exemplos** - Outros casos

In [ ]:
a = np.array([[1, 1, 1], [0, 0, 0]])
print(a)

[[1 1 1]
 [0 0 0]]


In [ ]:
np.linalg.matrix_rank(a)

1

In [ ]:
a = np.array([[1, 1, 1],
              [1, 1, 10],
              [1, 1, 15],
              [1, 2,  2]])
a

array([[ 1,  1,  1],
       [ 1,  1, 10],
       [ 1,  1, 15],
       [ 1,  2,  2]])

In [ ]:
np.linalg.matrix_rank(a)

3

In [ ]:
np.linalg.matrix_rank(a.reshape(2,6))

2

## Diagonal de uma matriz quadrada

- Podemos acessar a diagonal principal de uma matriz quadrada e transformá-la em um vetor usando o método `.diagonal`.

## Ajuda

```
import numpy as np
help(np.diagonal)
```

**Exemplos** - Observe abaixo

In [ ]:
# Criando uma matriz (3,3)
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

## Diagonal principal
a.diagonal()

array([1, 5, 9])

In [ ]:
print(a)
# A diagonal logo acima da diagonal principal
a.diagonal(offset=1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([3])

In [ ]:
# A Diagonal logo abaixo da diagonal principal
print(a)
a.diagonal(offset=-1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


array([4, 8])

In [ ]:
# A Diagonal mais distante abaixo da diagonal principal
a.diagonal(offset=-2)

array([7])

# Traço de uma matriz quadrada

- O traço de uma matriz quadrada é a soma dos valores dos elementos da diagonal principal.

- Podemos usar o método `.trace` para calcular esse número.

## Ajuda

```
import numpy as np
help(np.trace)
```


In [ ]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Traço - somando os elementos da diagonal principal
sum(a.diagonal())

15

In [ ]:
# Usando o método trace
a.trace()

15

# Determinante de uma matriz quadrada

- O determinante é um número associado a uma matriz quadrada: $A_{nn}$. Ele tem relação com condição de independência linear dos vetores linha e coluna.
- Por exemplo, o determinante de uma matriz $2 \times 2$ é:
\begin{equation}
    \begin{vmatrix}
        a & b\\
        c & d\\
    \end{vmatrix} = ad - bc
\end{equation}

- Uma expressão geral, para quaisquer $n$ é dada pelo Método do LaPlace:

$$|A|=\sum_{i=1}^k a_{ij} C_{ij},$$
onde $C_{ij}=(-1)^{i+j}M_{ij}$ é o cofator de $A_{ij}$ e $M_{ij}$ é uma matrix formada pela exclusão da linha $i$ e coluna $j$ de $A$.

No `numpy` usamos o método `numpy.linalg.det`.

## Ajuda

```
import numpy as np
help(np.linalg.det)
```


## Exercício

Dada a matriz

\begin{equation}
    A =
    \begin{bmatrix}
        1 & 2\\
        1 & 4\\
    \end{bmatrix},
\end{equation}

calcule o determinante.

In [ ]:
# Usando o método numpy.linalg.det
a = np.array([[1, 2],
              [1, 4]])

# Determinante
np.linalg.det(a)

2.0

In [ ]:
# Uma nova matriz (4,4)
b = np.array([[1, 2, 3, 4],
              [2, 4, 6, 0],
              [3, 8, 9, 2],
              [1, 1, 2, 1]])
print(b)
# Determinante
np.linalg.det(b)

[[1 2 3 4]
 [2 4 6 0]
 [3 8 9 2]
 [1 1 2 1]]


15.999999999999998

In [ ]:
# Uma nova matriz (2,2)
b = np.array([[1,2], [2,4]])
print(b)
# Determinante
np.linalg.det(b)

[[1 2]
 [2 4]]


0.0

# Revisitando operações matemáticas diversas com matrizes

## Adição e subtração

In [ ]:
a = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 2]])

b = np.array([[1, 3, 1],
              [1, 3, 1],
              [1, 3, 8]])

In [ ]:
np.add(a, b) # Adição

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
a + b

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [ ]:
np.subtract(a, b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

In [ ]:
a - b

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])

## Multiplicação matricial

$$C(i,j)=\sum_{k=1}^K A(i,k)B(k,j)$$

- Podemos usar o método `.dot` ou o operador `@`


In [ ]:
a = np.array([[1, 1, 1],
              [1, 1, 1],
              [1, 1, 2]])

b = np.array([[1, 3, 1],
              [1, 3, 1],
              [1, 3, 8]])

In [ ]:
print(f'A =\n {a} \n\n B = \n {b}')

A =
 [[1 1 1]
 [1 1 1]
 [1 1 2]] 

 B = 
 [[1 3 1]
 [1 3 1]
 [1 3 8]]


In [ ]:
np.dot(a, b)

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

In [ ]:
a @ b

array([[ 3,  9, 10],
       [ 3,  9, 10],
       [ 4, 12, 18]])

- Note a diferença da multiplicação de elemento por elemento

In [ ]:
print(f'A =\n {a} \n\n B = \n {b}')

# E se ao invés de @ usássemos *:
a * b

A =
 [[1 1 1]
 [1 1 1]
 [1 1 2]] 

 B = 
 [[1 3 1]
 [1 3 1]
 [1 3 8]]


array([[ 1,  3,  1],
       [ 1,  3,  1],
       [ 1,  3, 16]])

# Inversão matricial

- A matriz inversa de uma matriz quadrada $A_{n,n}$ é uma segunda matriz denotada de $A^{-1}$, tal que a equação abaixo sempre será válida:

$$A A^{-1} = A^{-1} A = I$$

- No entanto, uma matriz quadrada pode não possuir uma inversa caso seu determinante seja nulo, dado o teorema abaixo:

$$ A^{-1} = \frac{1}{|A|} \hat{A}  $$

Onde $|A|$ é o determinante de $A$ e $\hat{A}$ é a matriz adjunta de A, ou seja,
a matriz transposta de todos os determinantes cofatores de A.

- Qual seria a matriz inversa de W:

\begin{equation}
    W =
    \begin{bmatrix}
        1 & 4\\
        2 & 5\\
    \end{bmatrix},
\end{equation}

- No `numpy` usamos o método `numpy.linalg.inv`.

## Ajuda

```
import numpy as np
help(np.linalg.inv)
```

**Exemplo** - Encotrar, se existir, a matriz inversa de W.

In [ ]:
w = np.array([[1, 4],
              [2, 5]])
w

array([[1, 4],
       [2, 5]])

In [ ]:
# Tentar inverter a matriz
np.linalg.inv(w)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [ ]:
w = np.array([[1, 2],
              [2, 4]])
w

array([[1, 2],
       [2, 4]])

In [ ]:
# Tentar inverter a matriz singular
np.linalg.inv(w)

In [ ]:
w = np.array([[1, 4],
              [2, 5]])
w

array([[1, 4],
       [2, 5]])

In [ ]:
# Vamos demonstrar a definição que a multiplicação de A por sua inversa ser igual a matriz identidade

q = w @ np.linalg.inv(w)
q.round(1)

array([[1., 0.],
       [0., 1.]])

**Exemplo** - uma matriz quadrada singular.

In [ ]:
a = np.matrix([[1, 4],
              [2, 8]])

# Determinante
np.linalg.det(a)

0.0

In [ ]:
np.linalg.inv(a)

## Autovalores e autovetores de matrizes quadradas

- **Transformações lineares** em álgebra linear são funções lineares que conduzem
vetores de um espaço vetorial para outro espaço vetorial.

- Há **transformações lineares proporcionais** que conduzem vetores entre espaços vetoriais de mesma dimensão $F: R^n \rightarrow R^n$. 

- Nesse grupo temos transformações lineares que projetam vetores de um espaço de origem para outro espaço de destino como múltiplos deles mesmo (autovetores),
onde os parâmetros múltiplicadores são conhecidos como $\lambda$ (autovalores):

$$ F: R^n \rightarrow R^n: F(v) = \lambda v \rightarrow  A v = \lambda v$$

A é uma matriz quadrada, $\lambda$ contêm os autovalores e $v$ autovetores representativos.

- A transformação linear sempre vai envolver uma matriz quadrada A, de modo que podemos resolvê-la para qualquer matriz quadrada.

No `numpy` usamos o método `numpy.linalg.eig`

**Exemplos** - calcular os autovalores e autovetores associados a matriz quadrada A.

In [ ]:
# Matriz 3 x 3
a = np.array([[1, -1, 3],
              [1, 1, 6],
              [3, 8, 9]])
a

array([[ 1, -1,  3],
       [ 1,  1,  6],
       [ 3,  8,  9]])

In [ ]:
# Retornar autovalores e autovetores
np.linalg.eig(a)

(array([0., 9.]), matrix([[-0.9701425 , -0.4472136 ],
         [ 0.24253563, -0.89442719]]))

In [ ]:
# Calculando e desconstruindo o resultado para duas variáveis
autovalor, autovetor = np.linalg.eig(a)

In [ ]:
autovalor

array([0., 9.])

In [ ]:
# Matriz de autovetores
autovetor

matrix([[-0.9701425 , -0.4472136 ],
        [ 0.24253563, -0.89442719]])

#### Array Multidimensionais - Empilhando matrizes - Arrays 3-D



In [ ]:
# Criando um Array que coleciona duas matrizes 3 x 3
a = np.array( [ [ [1,2,3], [5,4,6], [7,8,9] ],  [ [0,1,1], [-1,4,3], [0,1,1] ]  ] )
print(a, a.shape, a.ndim)


[[[ 1  2  3]
  [ 5  4  6]
  [ 7  8  9]]

 [[ 0  1  1]
  [-1  4  3]
  [ 0  1  1]]] (2, 3, 3) 3


In [ ]:
# Criando um Array que coleciona três matrizes 2 x 2
a = np.array( [ [ [0,1], [-1,1]  ], [ [2,3], [4,5]], [ [6,7], [0,1]]    ]  )
print(a, a.shape, a.ndim)

[[[ 0  1]
  [-1  1]]

 [[ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 0  1]]] (3, 2, 2) 3


In [ ]:
# Criando um Array que coleciona três matrizes 2 x 3 - Array 3-D
b = np.array([ [ [0,1,4], [1,2,5]   ], [ [0,3,4], [0,-1,-2]   ], [ [0,1,1], [0,-1,-1]   ]   ])
print(b,b.shape, b.ndim)

[[[ 0  1  4]
  [ 1  2  5]]

 [[ 0  3  4]
  [ 0 -1 -2]]

 [[ 0  1  1]
  [ 0 -1 -1]]] (3, 2, 3) 3


In [ ]:
# Propriedades da Array
print(f"Total de elementos: {b.size} \n Formato: {b.shape} \n Dimensão: {b.ndim}")

Total de elementos: 18 
 Formato: (3, 2, 3) 
 Dimensão: 3


# Ciclos

#### Ciclos sobre Arrays 1-D - vetores

- Iteração sobre o espaço-linha.

In [ ]:
a = np.array([2,4,7])
print(a, a.shape, a.ndim)

[2 4 7] (3,) 1


In [ ]:
# Iteramos (percorremos) cada elemento da array
# Similar a um loop sobre uma lista
for i in a:
  print(i) 

2
4
7


In [ ]:
print(a)
# Acumular o produto dos elementos da array
produto = 1
for i in a:
  produto *= i

print(produto)

[2 4 7]
56


#### Ciclos sobre Arrays 2-D - matrizes

- Iterações sobre os espaço-linha e espaço-coluna.

In [ ]:
# Considere uma matriz 2 x 2 - Array 2-D
a = np.array([ [0,4], [-1,-2] ])
print(a, a.shape, a.ndim)

[[ 0  4]
 [-1 -2]] (2, 2) 2


In [ ]:
# Percorrer linha por linha
for i in a:
  print(f"linha: {i}") 

linha: [0 4]
linha: [-1 -2]


#### Loop aninhado

- Primeiro ciclo - iteramos (percorremos) cada linha da matriz - Array 2-D
- Segundo ciclo - iteramos (percorremos) cada elemento da linha selecionada

In [ ]:
# Matriz
print(a)

# Primeiro ciclo -  Percorrer linha por linha
for i in a:
  print(f"linha: {i}") 
  # Segundo ciclo (aninhado) -  percorrer cada elemento j da linha i
  for j in i:
    print(f"elemento: {j}")


[[ 0  4]
 [-1 -2]]
linha: [0 4]
elemento: 0
elemento: 4
linha: [-1 -2]
elemento: -1
elemento: -2


In [ ]:
# Matriz
print(a)

# Somar todos os elementos da matriz
soma = 0

# ciclo aninhado
for i in a:
  for j in i:
    soma += j

# Soma de todos os elementos da matriz
print(soma)

[[ 0  4]
 [-1 -2]]
1


In [ ]:
# Considere uma matriz 2 x 3
a = np.array([[0,4,3], [-1,-2,0]])
print(a, a.shape, a.ndim)

[[ 0  4  3]
 [-1 -2  0]] (2, 3) 2


In [ ]:
# Ciclo aninhado - iterar cada elemento da matriz
# Percorrer cada linha
for r in a:
  # Percorrer cada elemento da linha
  for i in r:
    print(i) 

0
4
3
-1
-2
0


#### Ciclos sobre Arrays 3-D - coleção de matrizes

- Iterações em três dimensões: espaço-linha e espaço-coluna de cada matriz e espaço-matriz.

In [ ]:
# Considere uma array com duas matrizes 2 x 3
a = np.array([ [ [1, 2, 3], [4, 5, 6] ], [ [7, 8, 9], [10, 11, 12] ] ])
print(a, a.shape, a.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] (2, 2, 3) 3


In [ ]:
# Percorrer cada matriz
for m in a:
  print(f"Matriz: {m}")

Matriz: [[1 2 3]
 [4 5 6]]
Matriz: [[ 7  8  9]
 [10 11 12]]


In [ ]:
# Percorrer cada linha de cada matriz
for m in a:
  print(f"Matriz: {m}")
  for r in m:
    print(f"Linha: {r}")

Matriz: [[1 2 3]
 [4 5 6]]
Linha: [1 2 3]
Linha: [4 5 6]
Matriz: [[ 7  8  9]
 [10 11 12]]
Linha: [7 8 9]
Linha: [10 11 12]


In [ ]:
# Percorrer cada elemento de uma linha de cada matriz
for m in a:
  print(f"Matriz: {m}")
  for r in m:
    print(f"Linha: {r}")
    for j in r:
      print(f"Elemento: {j}")

Matriz: [[1 2 3]
 [4 5 6]]
Linha: [1 2 3]
Elemento: 1
Elemento: 2
Elemento: 3
Linha: [4 5 6]
Elemento: 4
Elemento: 5
Elemento: 6
Matriz: [[ 7  8  9]
 [10 11 12]]
Linha: [7 8 9]
Elemento: 7
Elemento: 8
Elemento: 9
Linha: [10 11 12]
Elemento: 10
Elemento: 11
Elemento: 12


In [ ]:
# Considere uma array com duas matrizes 2 x 3
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Percorrer cada matriz
for m in a:
  # Percorrer cada linha
  for r in m:
    print(r) 

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [ ]:
# Considere uma array com duas matrizes 2 x 3
a = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Percorrer cada matriz
for m in a:
  # Percorrer cada linha
  for r in m:
    # Percorrer cada elemento da linha
    for i in r:
      print(i)

#### Ciclos usando métodos auxiliares

- O método `.nditer` (iteração multidimensional) já faz a abstração de loop aninhando, permitindo iterar cada elemento da array.

In [ ]:
# Considere uma array 3-D que empilha duas matrizes 2 x 2
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
# Iterando cada elemento da array
for x in np.nditer(a):
  print(x)

# Vetorização e Desempenho no NumPy

- O Numpy foi projetado para ser eficiente com operações envolvendo matrizes, vetores e arrays. Ou seja, a maior parte do processamento no Numpy é vetorizado.

A vetorização envolve operações matemáticas sobre matrizes inteiras, em vez de seus elementos individuais, acelerando o desempenho.

Ciclos em arrays, listas ou dicionários do Python podem ser lentos. Assim, as operações vetorizadas em Numpy são mapeadas para código C altamente otimizado, tornando-as muito mais rápidas, especiamente quando temos milhões de dados.

#### Iteração padrão lenta

- Loop com muitos dados

In [ ]:
# Importar pacote time
import time as tm

# Marca tempo de início
start_time = tm.time()

# 5 milhões de iterações
n = 5000000

# Criar uma lista com 5 mi de elementos
data = range(n)

# Valor inicial
number = 1

# Loop sobre a lista - acumular a multiplacação por 1.0000001
for i in data:
  number *= 1.0000001

# Marcar tempo final
end_time = tm.time()

# Resultado
print(number)
print(f"Tempo de execução = {end_time - start_time}")

1.648721229963447
Tempo de execução = 0.5155990123748779


Iteração rápida com NumPy
Loop com muitos dados

In [ ]:
# Importar pacote time
import time as tm
import numpy as np

# Marca tempo de início
start_time = tm.time()

# 5 milhões de iterações
n = 5000000

# Valor inicial
number = 1

# O método .power criar uma array com "n" elementos e multiplica cada elemento
# por um fator
# Loop sobre a lista - acumular a multiplacação por 1.0000001
number *= np.power(1.0000001, n)

# Marcar tempo final
end_time = tm.time()

# Resultado
print(number)
print(f"Tempo de execução = {end_time - start_time}")

1.6487212299634166
Tempo de execução = 0.0002167224884033203



#### Exemplo

## Solução de sistemas de equações lineares

Resolva o seguinte sistema de equação 2 x 2 no Python a partir da álgebra linear para matrizes quadradas.

\begin{equation}
\left\{
\begin{array}{r}
2x-5y=11\\
3x+6y=3
\end{array}
\right.
\end{equation}

\begin{equation}
    A =
    \begin{bmatrix}
    2 & -5\\
    3 & 6\\
    \end{bmatrix}
    \qquad    b =
    \begin{bmatrix}
    11\\
    3\\
    \end{bmatrix}
    \qquad    x =
    \begin{bmatrix}
    x\\
    y\\
    \end{bmatrix}
\end{equation}

### Forma matricial

$$ Ax = b  $$

#### Solução por inversão de matriz

$$x = A^{-1}b$$


In [ ]:
a = np.array([[2, -5],
              [3, 6]])
# Na forma coluna
b = np.array([[11],
              [3]])
print(f'Matriz A\n {a}\n')

Matriz A
 [[ 2 -5]
 [ 3  6]]



In [ ]:
print(f'Matriz b\n {b}')

Matriz b
 [[11]
 [ 3]]


In [ ]:
# Matriz inversa de A
a_inv = np.linalg.inv(a)
a_inv


array([[ 0.22222222,  0.18518519],
       [-0.11111111,  0.07407407]])

**Solução** 

In [ ]:
# Resolução
x = a_inv @ b
print(f'x={float(x[0]):.2f} e y={float(x[1]):.2f}')

x=3.00 e y=-1.00



## Referências

- Chen (2018). *Pandas for everyone: python data analysis* Addison-Wesley Professional.
- Marcondes (2018). *Matemática com Python*. São Paulo: Novatec.
- Menezes (2019). *Introdução à programação com Python*. 3 ed. São Paulo: Novatec.
- http://cs231n.github.io/python-numpy-tutorial/
- https://www.oreilly.com/library/view/machine-learning-with/9781491989371/ch01.html
- http://www.ie.ufrj.br/intranet/ie/userintranet/hpp/arquivos/matriz_insumo_pruduto_resumo.pdf
- https://numpy.org/doc/stable/user/absolute_beginners.html

